TERMUX_SUBPKG_DESCRIPTION="Documentation for the latex packages of TeX Live. Contains docs for latex packages starting with l-z."
TERMUX_SUBPKG_DEPENDS="texlive-full"
TERMUX_SUBPKG_INCLUDE="share/texlive/texmf-dist/doc/latex/l2picfaq
share/texlive/texmf-dist/doc/latex/l2tabu
share/texlive/texmf-dist/doc/latex/l2tabu-english
share/texlive/texmf-dist/doc/latex/l2tabu-french
share/texlive/texmf-dist/doc/latex/l2tabu-italian
share/texlive/texmf-dist/doc/latex/l2tabu-spanish
share/texlive/texmf-dist/doc/latex/l3build
share/texlive/texmf-dist/doc/latex/l3experimental
share/texlive/texmf-dist/doc/latex/l3kernel
share/texlive/texmf-dist/doc/latex/l3packages
share/texlive/texmf-dist/doc/latex/labbook
share/texlive/texmf-dist/doc/latex/labels
share/texlive/texmf-dist/doc/latex/labyrinth
share/texlive/texmf-dist/doc/latex/ladder
share/texlive/texmf-dist/doc/latex/lapdf
share/texlive/texmf-dist/doc/latex/lastpackage
share/texlive/texmf-dist/doc/latex/lastpage
share/texlive/texmf-dist/doc/latex/latex-bib-ex
share/texlive/texmf-dist/doc/latex/latex-bib2-ex
share/texlive/texmf-dist/doc/latex/latex-brochure
share/texlive/texmf-dist/doc/latex/latex-course
share/texlive/texmf-dist/doc/latex/latex-doc-ptr
share/texlive/texmf-dist/doc/latex/latex-graphics-companion
share/texlive/texmf-dist/doc/latex/latex-referenz
share/texlive/texmf-dist/doc/latex/latex-tabellen
share/texlive/texmf-dist/doc/latex/latex-tds
share/texlive/texmf-dist/doc/latex/latex-veryshortguide
share/texlive/texmf-dist/doc/latex/latex-web-companion
share/texlive/texmf-dist/doc/latex/latex2e-help-texinfo
share/texlive/texmf-dist/doc/latex/latex2e-help-texinfo-fr
share/texlive/texmf-dist/doc/latex/latex2e-help-texinfo-spanish
share/texlive/texmf-dist/doc/latex/latex4wp
share/texlive/texmf-dist/doc/latex/latex4wp-it
share/texlive/texmf-dist/doc/latex/latexbangla
share/texlive/texmf-dist/doc/latex/latexbug
share/texlive/texmf-dist/doc/latex/latexcheat
share/texlive/texmf-dist/doc/latex/latexcheat-de
share/texlive/texmf-dist/doc/latex/latexcheat-esmx
share/texlive/texmf-dist/doc/latex/latexcheat-ptbr
share/texlive/texmf-dist/doc/latex/latexcourse-rug
share/texlive/texmf-dist/doc/latex/latexdemo
share/texlive/texmf-dist/doc/latex/latexfileinfo-pkgs
share/texlive/texmf-dist/doc/latex/latexgit
share/texlive/texmf-dist/doc/latex/layaureo
share/texlive/texmf-dist/doc/latex/layouts
share/texlive/texmf-dist/doc/latex/lazylist
share/texlive/texmf-dist/doc/latex/lcd
share/texlive/texmf-dist/doc/latex/lcg
share/texlive/texmf-dist/doc/latex/lcyw
share/texlive/texmf-dist/doc/latex/leading
share/texlive/texmf-dist/doc/latex/leadsheets
share/texlive/texmf-dist/doc/latex/leaflet
share/texlive/texmf-dist/doc/latex/ledmac
share/texlive/texmf-dist/doc/latex/leftidx
share/texlive/texmf-dist/doc/latex/leipzig
share/texlive/texmf-dist/doc/latex/lengthconvert
share/texlive/texmf-dist/doc/latex/lettre
share/texlive/texmf-dist/doc/latex/lettrine
share/texlive/texmf-dist/doc/latex/lewis
share/texlive/texmf-dist/doc/latex/lexikon
share/texlive/texmf-dist/doc/latex/lexref
share/texlive/texmf-dist/doc/latex/lgreek
share/texlive/texmf-dist/doc/latex/lhelp
share/texlive/texmf-dist/doc/latex/libgreek
share/texlive/texmf-dist/doc/latex/limap
share/texlive/texmf-dist/doc/latex/linegoal
share/texlive/texmf-dist/doc/latex/lineno
share/texlive/texmf-dist/doc/latex/ling-macros
share/texlive/texmf-dist/doc/latex/linguex
share/texlive/texmf-dist/doc/latex/linop
share/texlive/texmf-dist/doc/latex/lion-msc
share/texlive/texmf-dist/doc/latex/lipsum
share/texlive/texmf-dist/doc/latex/lisp-on-tex
share/texlive/texmf-dist/doc/latex/listbib
share/texlive/texmf-dist/doc/latex/listing
share/texlive/texmf-dist/doc/latex/listings
share/texlive/texmf-dist/doc/latex/listings-ext
share/texlive/texmf-dist/doc/latex/listlbls
share/texlive/texmf-dist/doc/latex/listliketab
share/texlive/texmf-dist/doc/latex/listofsymbols
share/texlive/texmf-dist/doc/latex/lithuanian
share/texlive/texmf-dist/doc/latex/liturg
share/texlive/texmf-dist/doc/latex/lkproof
share/texlive/texmf-dist/doc/latex/lmake
share/texlive/texmf-dist/doc/latex/lni
share/texlive/texmf-dist/doc/latex/locality
share/texlive/texmf-dist/doc/latex/localloc
share/texlive/texmf-dist/doc/latex/logbox
share/texlive/texmf-dist/doc/latex/logical-markup-utils
share/texlive/texmf-dist/doc/latex/logicproof
share/texlive/texmf-dist/doc/latex/logicpuzzle
share/texlive/texmf-dist/doc/latex/logpap
share/texlive/texmf-dist/doc/latex/logreq
share/texlive/texmf-dist/doc/latex/longdivision
share/texlive/texmf-dist/doc/latex/longfbox
share/texlive/texmf-dist/doc/latex/longfigure
share/texlive/texmf-dist/doc/latex/longnamefilelist
share/texlive/texmf-dist/doc/latex/loops
share/texlive/texmf-dist/doc/latex/lpic
share/texlive/texmf-dist/doc/latex/lplfitch
share/texlive/texmf-dist/doc/latex/lps
share/texlive/texmf-dist/doc/latex/lroundrect
share/texlive/texmf-dist/doc/latex/lsc
share/texlive/texmf-dist/doc/latex/lshort-bulgarian
share/texlive/texmf-dist/doc/latex/lshort-chinese
share/texlive/texmf-dist/doc/latex/lshort-czech
share/texlive/texmf-dist/doc/latex/lshort-dutch
share/texlive/texmf-dist/doc/latex/lshort-english
share/texlive/texmf-dist/doc/latex/lshort-estonian
share/texlive/texmf-dist/doc/latex/lshort-finnish
share/texlive/texmf-dist/doc/latex/lshort-french
share/texlive/texmf-dist/doc/latex/lshort-german
share/texlive/texmf-dist/doc/latex/lshort-italian
share/texlive/texmf-dist/doc/latex/lshort-japanese
share/texlive/texmf-dist/doc/latex/lshort-korean
share/texlive/texmf-dist/doc/latex/lshort-mongol
share/texlive/texmf-dist/doc/latex/lshort-persian
share/texlive/texmf-dist/doc/latex/lshort-polish
share/texlive/texmf-dist/doc/latex/lshort-portuguese
share/texlive/texmf-dist/doc/latex/lshort-russian
share/texlive/texmf-dist/doc/latex/lshort-slovak
share/texlive/texmf-dist/doc/latex/lshort-slovenian
share/texlive/texmf-dist/doc/latex/lshort-spanish
share/texlive/texmf-dist/doc/latex/lshort-thai
share/texlive/texmf-dist/doc/latex/lshort-turkish
share/texlive/texmf-dist/doc/latex/lshort-ukr
share/texlive/texmf-dist/doc/latex/lshort-vietnamese
share/texlive/texmf-dist/doc/latex/lstaddons
share/texlive/texmf-dist/doc/latex/lstbayes
share/texlive/texmf-dist/doc/latex/lt3graph
share/texlive/texmf-dist/doc/latex/ltablex
share/texlive/texmf-dist/doc/latex/ltabptch
share/texlive/texmf-dist/doc/latex/ltb2bib
share/texlive/texmf-dist/doc/latex/ltxdockit
share/texlive/texmf-dist/doc/latex/ltxindex
share/texlive/texmf-dist/doc/latex/ltxkeys
share/texlive/texmf-dist/doc/latex/ltxnew
share/texlive/texmf-dist/doc/latex/ltxtools
share/texlive/texmf-dist/doc/latex/lualatex-doc-de
share/texlive/texmf-dist/doc/latex/lwarp
share/texlive/texmf-dist/doc/latex/macros2e
share/texlive/texmf-dist/doc/latex/macroswap
share/texlive/texmf-dist/doc/latex/mafr
share/texlive/texmf-dist/doc/latex/magaz
share/texlive/texmf-dist/doc/latex/mailing
share/texlive/texmf-dist/doc/latex/mailmerge
share/texlive/texmf-dist/doc/latex/makebarcode
share/texlive/texmf-dist/doc/latex/makebase
share/texlive/texmf-dist/doc/latex/makebox
share/texlive/texmf-dist/doc/latex/makecell
share/texlive/texmf-dist/doc/latex/makecmds
share/texlive/texmf-dist/doc/latex/makeglos
share/texlive/texmf-dist/doc/latex/makeplot
share/texlive/texmf-dist/doc/latex/makeshape
share/texlive/texmf-dist/doc/latex/mandi
share/texlive/texmf-dist/doc/latex/manuscript
share/texlive/texmf-dist/doc/latex/margbib
share/texlive/texmf-dist/doc/latex/marginfix
share/texlive/texmf-dist/doc/latex/marginnote
share/texlive/texmf-dist/doc/latex/markdown
share/texlive/texmf-dist/doc/latex/matc3
share/texlive/texmf-dist/doc/latex/matc3mem
share/texlive/texmf-dist/doc/latex/math-e
share/texlive/texmf-dist/doc/latex/math-into-latex-4
share/texlive/texmf-dist/doc/latex/mathalfa
share/texlive/texmf-dist/doc/latex/mathastext
share/texlive/texmf-dist/doc/latex/mathcomp
share/texlive/texmf-dist/doc/latex/mathexam
share/texlive/texmf-dist/doc/latex/mathpartir
share/texlive/texmf-dist/doc/latex/mathpazo
share/texlive/texmf-dist/doc/latex/mathpunctspace
share/texlive/texmf-dist/doc/latex/maths-symbols
share/texlive/texmf-dist/doc/latex/mathspic
share/texlive/texmf-dist/doc/latex/mathtools
share/texlive/texmf-dist/doc/latex/matlab-prettifier
share/texlive/texmf-dist/doc/latex/mattens
share/texlive/texmf-dist/doc/latex/maybemath
share/texlive/texmf-dist/doc/latex/mbenotes
share/texlive/texmf-dist/doc/latex/mcaption
share/texlive/texmf-dist/doc/latex/mceinleger
share/texlive/texmf-dist/doc/latex/mcexam
share/texlive/texmf-dist/doc/latex/mcite
share/texlive/texmf-dist/doc/latex/mciteplus
share/texlive/texmf-dist/doc/latex/mcmthesis
share/texlive/texmf-dist/doc/latex/mdframed
share/texlive/texmf-dist/doc/latex/mdputu
share/texlive/texmf-dist/doc/latex/mdsymbol
share/texlive/texmf-dist/doc/latex/mdwtools
share/texlive/texmf-dist/doc/latex/media9
share/texlive/texmf-dist/doc/latex/medstarbeamer
share/texlive/texmf-dist/doc/latex/meetingmins
share/texlive/texmf-dist/doc/latex/memexsupp
share/texlive/texmf-dist/doc/latex/memoir
share/texlive/texmf-dist/doc/latex/memory
share/texlive/texmf-dist/doc/latex/mentis
share/texlive/texmf-dist/doc/latex/menu
share/texlive/texmf-dist/doc/latex/menukeys
share/texlive/texmf-dist/doc/latex/metalogo
share/texlive/texmf-dist/doc/latex/metaplot
share/texlive/texmf-dist/doc/latex/method
share/texlive/texmf-dist/doc/latex/metre
share/texlive/texmf-dist/doc/latex/metrix
share/texlive/texmf-dist/doc/latex/mfirstuc
share/texlive/texmf-dist/doc/latex/mflogo
share/texlive/texmf-dist/doc/latex/mfnfss
share/texlive/texmf-dist/doc/latex/mfpic4ode
share/texlive/texmf-dist/doc/latex/mftinc
share/texlive/texmf-dist/doc/latex/mgltex
share/texlive/texmf-dist/doc/latex/mhchem
share/texlive/texmf-dist/doc/latex/mhequ
share/texlive/texmf-dist/doc/latex/microtype
share/texlive/texmf-dist/doc/latex/microtype-de
share/texlive/texmf-dist/doc/latex/midpage
share/texlive/texmf-dist/doc/latex/miller
share/texlive/texmf-dist/doc/latex/milog
share/texlive/texmf-dist/doc/latex/minibox
share/texlive/texmf-dist/doc/latex/minidocument
share/texlive/texmf-dist/doc/latex/minipage-marginpar
share/texlive/texmf-dist/doc/latex/miniplot
share/texlive/texmf-dist/doc/latex/minitoc
share/texlive/texmf-dist/doc/latex/minorrevision
share/texlive/texmf-dist/doc/latex/minted
share/texlive/texmf-dist/doc/latex/minutes
share/texlive/texmf-dist/doc/latex/mla-paper
share/texlive/texmf-dist/doc/latex/mlist
share/texlive/texmf-dist/doc/latex/mltex
share/texlive/texmf-dist/doc/latex/mmap
share/texlive/texmf-dist/doc/latex/mnotes
share/texlive/texmf-dist/doc/latex/mnras
share/texlive/texmf-dist/doc/latex/mnsymbol
share/texlive/texmf-dist/doc/latex/moderncv
share/texlive/texmf-dist/doc/latex/moderntimeline
share/texlive/texmf-dist/doc/latex/modiagram
share/texlive/texmf-dist/doc/latex/modref
share/texlive/texmf-dist/doc/latex/modroman
share/texlive/texmf-dist/doc/latex/modular
share/texlive/texmf-dist/doc/latex/mongolian-babel
share/texlive/texmf-dist/doc/latex/monofill
share/texlive/texmf-dist/doc/latex/montex
share/texlive/texmf-dist/doc/latex/moodle
share/texlive/texmf-dist/doc/latex/moreenum
share/texlive/texmf-dist/doc/latex/morefloats
share/texlive/texmf-dist/doc/latex/morehype
share/texlive/texmf-dist/doc/latex/moresize
share/texlive/texmf-dist/doc/latex/moreverb
share/texlive/texmf-dist/doc/latex/morewrites
share/texlive/texmf-dist/doc/latex/movie15
share/texlive/texmf-dist/doc/latex/mparhack
share/texlive/texmf-dist/doc/latex/mpgraphics
share/texlive/texmf-dist/doc/latex/mpostinl
share/texlive/texmf-dist/doc/latex/ms
share/texlive/texmf-dist/doc/latex/msc
share/texlive/texmf-dist/doc/latex/msg
share/texlive/texmf-dist/doc/latex/mslapa
share/texlive/texmf-dist/doc/latex/msu-thesis
share/texlive/texmf-dist/doc/latex/mtgreek
share/texlive/texmf-dist/doc/latex/mucproc
share/texlive/texmf-dist/doc/latex/mugsthesis
share/texlive/texmf-dist/doc/latex/multenum
share/texlive/texmf-dist/doc/latex/multiaudience
share/texlive/texmf-dist/doc/latex/multibbl
share/texlive/texmf-dist/doc/latex/multibib
share/texlive/texmf-dist/doc/latex/multibibliography
share/texlive/texmf-dist/doc/latex/multicap
share/texlive/texmf-dist/doc/latex/multidef
share/texlive/texmf-dist/doc/latex/multienv
share/texlive/texmf-dist/doc/latex/multiobjective
share/texlive/texmf-dist/doc/latex/multirow
share/texlive/texmf-dist/doc/latex/munich
share/texlive/texmf-dist/doc/latex/musixguit
share/texlive/texmf-dist/doc/latex/musuos
share/texlive/texmf-dist/doc/latex/muthesis
share/texlive/texmf-dist/doc/latex/mversion
share/texlive/texmf-dist/doc/latex/mwcls
share/texlive/texmf-dist/doc/latex/mwe
share/texlive/texmf-dist/doc/latex/mweights
share/texlive/texmf-dist/doc/latex/mychemistry
share/texlive/texmf-dist/doc/latex/mycv
share/texlive/texmf-dist/doc/latex/mylatexformat
share/texlive/texmf-dist/doc/latex/nag
share/texlive/texmf-dist/doc/latex/nameauth
share/texlive/texmf-dist/doc/latex/namespc
share/texlive/texmf-dist/doc/latex/natbib
share/texlive/texmf-dist/doc/latex/natded
share/texlive/texmf-dist/doc/latex/nath
share/texlive/texmf-dist/doc/latex/nature
share/texlive/texmf-dist/doc/latex/navydocs
share/texlive/texmf-dist/doc/latex/ncclatex
share/texlive/texmf-dist/doc/latex/ncctools
share/texlive/texmf-dist/doc/latex/nddiss
share/texlive/texmf-dist/doc/latex/ndsu-thesis
share/texlive/texmf-dist/doc/latex/needspace
share/texlive/texmf-dist/doc/latex/neuralnetwork
share/texlive/texmf-dist/doc/latex/nevelok
share/texlive/texmf-dist/doc/latex/newcommand
share/texlive/texmf-dist/doc/latex/newenviron
share/texlive/texmf-dist/doc/latex/newfile
share/texlive/texmf-dist/doc/latex/newlfm
share/texlive/texmf-dist/doc/latex/newspaper
share/texlive/texmf-dist/doc/latex/newunicodechar
share/texlive/texmf-dist/doc/latex/newvbtm
share/texlive/texmf-dist/doc/latex/newverbs
share/texlive/texmf-dist/doc/latex/nfssext-cfr
share/texlive/texmf-dist/doc/latex/nicefilelist
share/texlive/texmf-dist/doc/latex/niceframe
share/texlive/texmf-dist/doc/latex/nicetext
share/texlive/texmf-dist/doc/latex/nih
share/texlive/texmf-dist/doc/latex/nihbiosketch
share/texlive/texmf-dist/doc/latex/nlctdoc
share/texlive/texmf-dist/doc/latex/nmbib
share/texlive/texmf-dist/doc/latex/noconflict
share/texlive/texmf-dist/doc/latex/noindentafter
share/texlive/texmf-dist/doc/latex/noitcrul
share/texlive/texmf-dist/doc/latex/nolbreaks
share/texlive/texmf-dist/doc/latex/nomencl
share/texlive/texmf-dist/doc/latex/nomentbl
share/texlive/texmf-dist/doc/latex/nonfloat
share/texlive/texmf-dist/doc/latex/nonumonpart
share/texlive/texmf-dist/doc/latex/nopageno
share/texlive/texmf-dist/doc/latex/normalcolor
share/texlive/texmf-dist/doc/latex/nostarch
share/texlive/texmf-dist/doc/latex/notes
share/texlive/texmf-dist/doc/latex/notes2bib
share/texlive/texmf-dist/doc/latex/notespages
share/texlive/texmf-dist/doc/latex/notoccite
share/texlive/texmf-dist/doc/latex/nowidow
share/texlive/texmf-dist/doc/latex/nox
share/texlive/texmf-dist/doc/latex/nrc
share/texlive/texmf-dist/doc/latex/ntgclass
share/texlive/texmf-dist/doc/latex/ntheorem
share/texlive/texmf-dist/doc/latex/ntheorem-vn
share/texlive/texmf-dist/doc/latex/nuc
share/texlive/texmf-dist/doc/latex/nucleardata
share/texlive/texmf-dist/doc/latex/numberedblock
share/texlive/texmf-dist/doc/latex/numericplots
share/texlive/texmf-dist/doc/latex/numname
share/texlive/texmf-dist/doc/latex/numprint
share/texlive/texmf-dist/doc/latex/numspell
share/texlive/texmf-dist/doc/latex/nwejm
share/texlive/texmf-dist/doc/latex/oberdiek
share/texlive/texmf-dist/doc/latex/objectz
share/texlive/texmf-dist/doc/latex/ocg-p
share/texlive/texmf-dist/doc/latex/ocgx
share/texlive/texmf-dist/doc/latex/ocgx2
share/texlive/texmf-dist/doc/latex/ocr-latex
share/texlive/texmf-dist/doc/latex/octavo
share/texlive/texmf-dist/doc/latex/oldstyle
share/texlive/texmf-dist/doc/latex/onlyamsmath
share/texlive/texmf-dist/doc/latex/onrannual
share/texlive/texmf-dist/doc/latex/opcit
share/texlive/texmf-dist/doc/latex/oplotsymbl
share/texlive/texmf-dist/doc/latex/opteng
share/texlive/texmf-dist/doc/latex/optidef
share/texlive/texmf-dist/doc/latex/optional
share/texlive/texmf-dist/doc/latex/options
share/texlive/texmf-dist/doc/latex/ordinalpt
share/texlive/texmf-dist/doc/latex/oscola
share/texlive/texmf-dist/doc/latex/ot-tableau
share/texlive/texmf-dist/doc/latex/othello
share/texlive/texmf-dist/doc/latex/othelloboard
share/texlive/texmf-dist/doc/latex/otibet
share/texlive/texmf-dist/doc/latex/oubraces
share/texlive/texmf-dist/doc/latex/outline
share/texlive/texmf-dist/doc/latex/outliner
share/texlive/texmf-dist/doc/latex/outlines
share/texlive/texmf-dist/doc/latex/overlays
share/texlive/texmf-dist/doc/latex/overpic
share/texlive/texmf-dist/doc/latex/pagecolor
share/texlive/texmf-dist/doc/latex/pagecont
share/texlive/texmf-dist/doc/latex/pagenote
share/texlive/texmf-dist/doc/latex/pagerange
share/texlive/texmf-dist/doc/latex/pageslts
share/texlive/texmf-dist/doc/latex/paper
share/texlive/texmf-dist/doc/latex/papercdcase
share/texlive/texmf-dist/doc/latex/papermas
share/texlive/texmf-dist/doc/latex/papertex
share/texlive/texmf-dist/doc/latex/paracol
share/texlive/texmf-dist/doc/latex/parades
share/texlive/texmf-dist/doc/latex/paralist
share/texlive/texmf-dist/doc/latex/parallel
share/texlive/texmf-dist/doc/latex/paresse
share/texlive/texmf-dist/doc/latex/parnotes
share/texlive/texmf-dist/doc/latex/parrun
share/texlive/texmf-dist/doc/latex/parselines
share/texlive/texmf-dist/doc/latex/parskip
share/texlive/texmf-dist/doc/latex/pas-cours
share/texlive/texmf-dist/doc/latex/pas-crosswords
share/texlive/texmf-dist/doc/latex/pas-cv
share/texlive/texmf-dist/doc/latex/pas-tableur
share/texlive/texmf-dist/doc/latex/patchcmd
share/texlive/texmf-dist/doc/latex/pauldoc
share/texlive/texmf-dist/doc/latex/pawpict
share/texlive/texmf-dist/doc/latex/pax
share/texlive/texmf-dist/doc/latex/pb-diagram
share/texlive/texmf-dist/doc/latex/pbox
share/texlive/texmf-dist/doc/latex/pbsheet
share/texlive/texmf-dist/doc/latex/pdf14
share/texlive/texmf-dist/doc/latex/pdfcomment
share/texlive/texmf-dist/doc/latex/pdfcprot
share/texlive/texmf-dist/doc/latex/pdfmarginpar
share/texlive/texmf-dist/doc/latex/pdfpagediff
share/texlive/texmf-dist/doc/latex/pdfpages
share/texlive/texmf-dist/doc/latex/pdfscreen
share/texlive/texmf-dist/doc/latex/pdfslide
share/texlive/texmf-dist/doc/latex/pdfsync
share/texlive/texmf-dist/doc/latex/pdftricks
share/texlive/texmf-dist/doc/latex/pdftricks2
share/texlive/texmf-dist/doc/latex/pdfwin
share/texlive/texmf-dist/doc/latex/pdfx
share/texlive/texmf-dist/doc/latex/pecha
share/texlive/texmf-dist/doc/latex/perfectcut
share/texlive/texmf-dist/doc/latex/perltex
share/texlive/texmf-dist/doc/latex/permute
share/texlive/texmf-dist/doc/latex/petiteannonce
share/texlive/texmf-dist/doc/latex/pfarrei
share/texlive/texmf-dist/doc/latex/pgf-blur
share/texlive/texmf-dist/doc/latex/pgf-soroban
share/texlive/texmf-dist/doc/latex/pgf-spectra
share/texlive/texmf-dist/doc/latex/pgf-umlcd
share/texlive/texmf-dist/doc/latex/pgf-umlsd
share/texlive/texmf-dist/doc/latex/pgfgantt
share/texlive/texmf-dist/doc/latex/pgfkeyx
share/texlive/texmf-dist/doc/latex/pgfopts
share/texlive/texmf-dist/doc/latex/pgfornament
share/texlive/texmf-dist/doc/latex/pgfplots
share/texlive/texmf-dist/doc/latex/phffullpagefigure
share/texlive/texmf-dist/doc/latex/phfnote
share/texlive/texmf-dist/doc/latex/phfparen
share/texlive/texmf-dist/doc/latex/phfqit
share/texlive/texmf-dist/doc/latex/phfquotetext
share/texlive/texmf-dist/doc/latex/phfsvnwatermark
share/texlive/texmf-dist/doc/latex/phfthm
share/texlive/texmf-dist/doc/latex/philex
share/texlive/texmf-dist/doc/latex/philosophersimprint
share/texlive/texmf-dist/doc/latex/phonenumbers
share/texlive/texmf-dist/doc/latex/phonrule
share/texlive/texmf-dist/doc/latex/photo
share/texlive/texmf-dist/doc/latex/physics
share/texlive/texmf-dist/doc/latex/piano
share/texlive/texmf-dist/doc/latex/picinpar
share/texlive/texmf-dist/doc/latex/pict2e
share/texlive/texmf-dist/doc/latex/pictexsum
share/texlive/texmf-dist/doc/latex/piff
share/texlive/texmf-dist/doc/latex/pigpen
share/texlive/texmf-dist/doc/latex/pinlabel
share/texlive/texmf-dist/doc/latex/pittetd
share/texlive/texmf-dist/doc/latex/pkgloader
share/texlive/texmf-dist/doc/latex/pkuthss
share/texlive/texmf-dist/doc/latex/placeins
share/texlive/texmf-dist/doc/latex/plantslabels
share/texlive/texmf-dist/doc/latex/plari
share/texlive/texmf-dist/doc/latex/plates
share/texlive/texmf-dist/doc/latex/platex-tools
share/texlive/texmf-dist/doc/latex/platexcheat
share/texlive/texmf-dist/doc/latex/play
share/texlive/texmf-dist/doc/latex/plweb
share/texlive/texmf-dist/doc/latex/pmgraph
share/texlive/texmf-dist/doc/latex/poemscol
share/texlive/texmf-dist/doc/latex/poetrytex
share/texlive/texmf-dist/doc/latex/polski
share/texlive/texmf-dist/doc/latex/polyglossia
share/texlive/texmf-dist/doc/latex/polynom
share/texlive/texmf-dist/doc/latex/polynomial
share/texlive/texmf-dist/doc/latex/polytable
share/texlive/texmf-dist/doc/latex/postcards
share/texlive/texmf-dist/doc/latex/powerdot
share/texlive/texmf-dist/doc/latex/powerdot-FUBerlin
share/texlive/texmf-dist/doc/latex/ppr-prv
share/texlive/texmf-dist/doc/latex/pracjourn
share/texlive/texmf-dist/doc/latex/preprint
share/texlive/texmf-dist/doc/latex/prerex
share/texlive/texmf-dist/doc/latex/presentations
share/texlive/texmf-dist/doc/latex/presentations-en
share/texlive/texmf-dist/doc/latex/pressrelease
share/texlive/texmf-dist/doc/latex/prettyref
share/texlive/texmf-dist/doc/latex/preview
share/texlive/texmf-dist/doc/latex/prftree
share/texlive/texmf-dist/doc/latex/printlen
share/texlive/texmf-dist/doc/latex/proba
share/texlive/texmf-dist/doc/latex/probsoln
share/texlive/texmf-dist/doc/latex/procIAGssymp
share/texlive/texmf-dist/doc/latex/productbox
share/texlive/texmf-dist/doc/latex/program
share/texlive/texmf-dist/doc/latex/progress
share/texlive/texmf-dist/doc/latex/progressbar
share/texlive/texmf-dist/doc/latex/proofread
share/texlive/texmf-dist/doc/latex/prooftrees
share/texlive/texmf-dist/doc/latex/properties
share/texlive/texmf-dist/doc/latex/proposal
share/texlive/texmf-dist/doc/latex/prosper
share/texlive/texmf-dist/doc/latex/protex
share/texlive/texmf-dist/doc/latex/protocol
share/texlive/texmf-dist/doc/latex/przechlewski-book
share/texlive/texmf-dist/doc/latex/psbao
share/texlive/texmf-dist/doc/latex/pseudocode
share/texlive/texmf-dist/doc/latex/psfrag
share/texlive/texmf-dist/doc/latex/psfrag-italian
share/texlive/texmf-dist/doc/latex/psfragx
share/texlive/texmf-dist/doc/latex/psgo
share/texlive/texmf-dist/doc/latex/psnfss
share/texlive/texmf-dist/doc/latex/pspicture
share/texlive/texmf-dist/doc/latex/pst-calendar
share/texlive/texmf-dist/doc/latex/pst-eucl-translation-bg
share/texlive/texmf-dist/doc/latex/pst-exa
share/texlive/texmf-dist/doc/latex/pst-intersect
share/texlive/texmf-dist/doc/latex/pst-layout
share/texlive/texmf-dist/doc/latex/pst-optexp
share/texlive/texmf-dist/doc/latex/pst-pdf
share/texlive/texmf-dist/doc/latex/pst-vectorian
share/texlive/texmf-dist/doc/latex/pst-vowel
share/texlive/texmf-dist/doc/latex/pst2pdf
share/texlive/texmf-dist/doc/latex/pstool
share/texlive/texmf-dist/doc/latex/pstricks_calcnotes
share/texlive/texmf-dist/doc/latex/pstring
share/texlive/texmf-dist/doc/latex/psu-thesis
share/texlive/texmf-dist/doc/latex/ptex2pdf
share/texlive/texmf-dist/doc/latex/ptptex
share/texlive/texmf-dist/doc/latex/punk-latex
share/texlive/texmf-dist/doc/latex/pxcjkcat
share/texlive/texmf-dist/doc/latex/pxgreeks
share/texlive/texmf-dist/doc/latex/pxpgfmark
share/texlive/texmf-dist/doc/latex/pxtatescale
share/texlive/texmf-dist/doc/latex/pygmentex
share/texlive/texmf-dist/doc/latex/python
share/texlive/texmf-dist/doc/latex/pythonhighlight
share/texlive/texmf-dist/doc/latex/pythontex
share/texlive/texmf-dist/doc/latex/qcircuit
share/texlive/texmf-dist/doc/latex/qcm
share/texlive/texmf-dist/doc/latex/qobitree
share/texlive/texmf-dist/doc/latex/qrcode
share/texlive/texmf-dist/doc/latex/qstest
share/texlive/texmf-dist/doc/latex/qsymbols
share/texlive/texmf-dist/doc/latex/qtree
share/texlive/texmf-dist/doc/latex/quicktype
share/texlive/texmf-dist/doc/latex/quotchap
share/texlive/texmf-dist/doc/latex/quoting
share/texlive/texmf-dist/doc/latex/quotmark
share/texlive/texmf-dist/doc/latex/r_und_s
share/texlive/texmf-dist/doc/latex/raleway
share/texlive/texmf-dist/doc/latex/ran_toks
share/texlive/texmf-dist/doc/latex/randbild
share/texlive/texmf-dist/doc/latex/randomwalk
share/texlive/texmf-dist/doc/latex/randtext
share/texlive/texmf-dist/doc/latex/rccol
share/texlive/texmf-dist/doc/latex/rcs
share/texlive/texmf-dist/doc/latex/rcs-multi
share/texlive/texmf-dist/doc/latex/rcsinfo
share/texlive/texmf-dist/doc/latex/readarray
share/texlive/texmf-dist/doc/latex/realboxes
share/texlive/texmf-dist/doc/latex/realscripts
share/texlive/texmf-dist/doc/latex/rec-thy
share/texlive/texmf-dist/doc/latex/recipe
share/texlive/texmf-dist/doc/latex/recipebook
share/texlive/texmf-dist/doc/latex/recipecard
share/texlive/texmf-dist/doc/latex/rectopma
share/texlive/texmf-dist/doc/latex/refcheck
share/texlive/texmf-dist/doc/latex/refenums
share/texlive/texmf-dist/doc/latex/reflectgraphics
share/texlive/texmf-dist/doc/latex/refman
share/texlive/texmf-dist/doc/latex/refstyle
share/texlive/texmf-dist/doc/latex/regcount
share/texlive/texmf-dist/doc/latex/regexpatch
share/texlive/texmf-dist/doc/latex/register
share/texlive/texmf-dist/doc/latex/regstats
share/texlive/texmf-dist/doc/latex/reledmac
share/texlive/texmf-dist/doc/latex/relenc
share/texlive/texmf-dist/doc/latex/relsize
share/texlive/texmf-dist/doc/latex/reotex
share/texlive/texmf-dist/doc/latex/repeatindex
share/texlive/texmf-dist/doc/latex/repltext
share/texlive/texmf-dist/doc/latex/resphilosophica
share/texlive/texmf-dist/doc/latex/revquantum
share/texlive/texmf-dist/doc/latex/revtex
share/texlive/texmf-dist/doc/latex/revtex4
share/texlive/texmf-dist/doc/latex/ribbonproofs
share/texlive/texmf-dist/doc/latex/rjlparshap
share/texlive/texmf-dist/doc/latex/rmathbr
share/texlive/texmf-dist/doc/latex/rmpage
share/texlive/texmf-dist/doc/latex/robustcommand
share/texlive/texmf-dist/doc/latex/robustindex
share/texlive/texmf-dist/doc/latex/romanbar
share/texlive/texmf-dist/doc/latex/romanbarpagenumber
share/texlive/texmf-dist/doc/latex/romanneg
share/texlive/texmf-dist/doc/latex/romannum
share/texlive/texmf-dist/doc/latex/rotfloat
share/texlive/texmf-dist/doc/latex/rotpages
share/texlive/texmf-dist/doc/latex/roundbox
share/texlive/texmf-dist/doc/latex/rputover
share/texlive/texmf-dist/doc/latex/rrgtrees
share/texlive/texmf-dist/doc/latex/rsc
share/texlive/texmf-dist/doc/latex/rterface
share/texlive/texmf-dist/doc/latex/rtkinenc
share/texlive/texmf-dist/doc/latex/rtklage
share/texlive/texmf-dist/doc/latex/rubik
share/texlive/texmf-dist/doc/latex/rulercompass
share/texlive/texmf-dist/doc/latex/russ
share/texlive/texmf-dist/doc/latex/rviewport
share/texlive/texmf-dist/doc/latex/rvwrite
share/texlive/texmf-dist/doc/latex/ryethesis
share/texlive/texmf-dist/doc/latex/sa-tikz
share/texlive/texmf-dist/doc/latex/sageep
share/texlive/texmf-dist/doc/latex/sanitize-umlaut
share/texlive/texmf-dist/doc/latex/sanskrit
share/texlive/texmf-dist/doc/latex/sansmath
share/texlive/texmf-dist/doc/latex/sapthesis
share/texlive/texmf-dist/doc/latex/sasnrdisplay
share/texlive/texmf-dist/doc/latex/sauerj
share/texlive/texmf-dist/doc/latex/sauterfonts
share/texlive/texmf-dist/doc/latex/savefnmark
share/texlive/texmf-dist/doc/latex/savetrees
share/texlive/texmf-dist/doc/latex/scale
share/texlive/texmf-dist/doc/latex/scalebar
share/texlive/texmf-dist/doc/latex/scalerel
share/texlive/texmf-dist/doc/latex/scanpages
share/texlive/texmf-dist/doc/latex/schemabloc
share/texlive/texmf-dist/doc/latex/schule
share/texlive/texmf-dist/doc/latex/schwalbe-chess
share/texlive/texmf-dist/doc/latex/sciposter
share/texlive/texmf-dist/doc/latex/sclang-prettifier
share/texlive/texmf-dist/doc/latex/scratch
share/texlive/texmf-dist/doc/latex/screenplay
share/texlive/texmf-dist/doc/latex/screenplay-pkg
share/texlive/texmf-dist/doc/latex/scrjrnl
share/texlive/texmf-dist/doc/latex/scrlttr2copy
share/texlive/texmf-dist/doc/latex/scsnowman
share/texlive/texmf-dist/doc/latex/sdrt
share/texlive/texmf-dist/doc/latex/sduthesis
share/texlive/texmf-dist/doc/latex/secdot
share/texlive/texmf-dist/doc/latex/section
share/texlive/texmf-dist/doc/latex/sectionbox
share/texlive/texmf-dist/doc/latex/sectsty
share/texlive/texmf-dist/doc/latex/seealso
share/texlive/texmf-dist/doc/latex/selectp
share/texlive/texmf-dist/doc/latex/semantic
share/texlive/texmf-dist/doc/latex/semantic-markup
share/texlive/texmf-dist/doc/latex/seminar
share/texlive/texmf-dist/doc/latex/semioneside
share/texlive/texmf-dist/doc/latex/semproc
share/texlive/texmf-dist/doc/latex/sepfootnotes
share/texlive/texmf-dist/doc/latex/sepnum
share/texlive/texmf-dist/doc/latex/seqsplit
share/texlive/texmf-dist/doc/latex/serbian-apostrophe
share/texlive/texmf-dist/doc/latex/serbian-date-lat
share/texlive/texmf-dist/doc/latex/serbian-def-cyr
share/texlive/texmf-dist/doc/latex/serbian-lig
share/texlive/texmf-dist/doc/latex/sesamanuel
share/texlive/texmf-dist/doc/latex/sesstime
share/texlive/texmf-dist/doc/latex/setdeck
share/texlive/texmf-dist/doc/latex/setspace
share/texlive/texmf-dist/doc/latex/seuthesis
share/texlive/texmf-dist/doc/latex/seuthesix
share/texlive/texmf-dist/doc/latex/sf298
share/texlive/texmf-dist/doc/latex/sffms
share/texlive/texmf-dist/doc/latex/sfg
share/texlive/texmf-dist/doc/latex/sgame
share/texlive/texmf-dist/doc/latex/shadethm
share/texlive/texmf-dist/doc/latex/shadow
share/texlive/texmf-dist/doc/latex/shadowtext
share/texlive/texmf-dist/doc/latex/shdoc
share/texlive/texmf-dist/doc/latex/shipunov
share/texlive/texmf-dist/doc/latex/shorttoc
share/texlive/texmf-dist/doc/latex/show2e
share/texlive/texmf-dist/doc/latex/showcharinbox
share/texlive/texmf-dist/doc/latex/showdim
share/texlive/texmf-dist/doc/latex/showexpl
share/texlive/texmf-dist/doc/latex/showlabels
share/texlive/texmf-dist/doc/latex/showtags
share/texlive/texmf-dist/doc/latex/shuffle
share/texlive/texmf-dist/doc/latex/sidecap
share/texlive/texmf-dist/doc/latex/sidenotes
share/texlive/texmf-dist/doc/latex/sides
share/texlive/texmf-dist/doc/latex/signchart
share/texlive/texmf-dist/doc/latex/silence
share/texlive/texmf-dist/doc/latex/simplecd
share/texlive/texmf-dist/doc/latex/simplecv
share/texlive/texmf-dist/doc/latex/simpler-wick
share/texlive/texmf-dist/doc/latex/simplewick
share/texlive/texmf-dist/doc/latex/simplified-latex
share/texlive/texmf-dist/doc/latex/sitem
share/texlive/texmf-dist/doc/latex/siunitx
share/texlive/texmf-dist/doc/latex/skak
share/texlive/texmf-dist/doc/latex/skb
share/texlive/texmf-dist/doc/latex/skdoc
share/texlive/texmf-dist/doc/latex/skeycommand
share/texlive/texmf-dist/doc/latex/skeyval
share/texlive/texmf-dist/doc/latex/skmath
share/texlive/texmf-dist/doc/latex/skrapport
share/texlive/texmf-dist/doc/latex/slantsc
share/texlive/texmf-dist/doc/latex/smalltableof
share/texlive/texmf-dist/doc/latex/smartdiagram
share/texlive/texmf-dist/doc/latex/smartref
share/texlive/texmf-dist/doc/latex/smartunits
share/texlive/texmf-dist/doc/latex/snapshot
share/texlive/texmf-dist/doc/latex/snotez
share/texlive/texmf-dist/doc/latex/songbook
share/texlive/texmf-dist/doc/latex/songs
share/texlive/texmf-dist/doc/latex/soton
share/texlive/texmf-dist/doc/latex/soul
share/texlive/texmf-dist/doc/latex/soup
share/texlive/texmf-dist/doc/latex/sourcecodepro
share/texlive/texmf-dist/doc/latex/sourcesanspro
share/texlive/texmf-dist/doc/latex/sourceserifpro
share/texlive/texmf-dist/doc/latex/spalign
share/texlive/texmf-dist/doc/latex/spanish-mx
share/texlive/texmf-dist/doc/latex/sparklines
share/texlive/texmf-dist/doc/latex/spath3
share/texlive/texmf-dist/doc/latex/sphack
share/texlive/texmf-dist/doc/latex/sphdthesis
share/texlive/texmf-dist/doc/latex/spie
share/texlive/texmf-dist/doc/latex/splitbib
share/texlive/texmf-dist/doc/latex/splitindex
share/texlive/texmf-dist/doc/latex/spot
share/texlive/texmf-dist/doc/latex/spotcolor
share/texlive/texmf-dist/doc/latex/spreadtab
share/texlive/texmf-dist/doc/latex/spverbatim
share/texlive/texmf-dist/doc/latex/sr-vorl
share/texlive/texmf-dist/doc/latex/srbook-mem
share/texlive/texmf-dist/doc/latex/srcltx
share/texlive/texmf-dist/doc/latex/sseq
share/texlive/texmf-dist/doc/latex/sslides
share/texlive/texmf-dist/doc/latex/stackengine
share/texlive/texmf-dist/doc/latex/stage
share/texlive/texmf-dist/doc/latex/standalone
share/texlive/texmf-dist/doc/latex/stanli
share/texlive/texmf-dist/doc/latex/statex
share/texlive/texmf-dist/doc/latex/statex2
share/texlive/texmf-dist/doc/latex/statistik
share/texlive/texmf-dist/doc/latex/stdclsdv
share/texlive/texmf-dist/doc/latex/stdpage
share/texlive/texmf-dist/doc/latex/steinmetz
share/texlive/texmf-dist/doc/latex/stellenbosch
share/texlive/texmf-dist/doc/latex/stex
share/texlive/texmf-dist/doc/latex/storebox
share/texlive/texmf-dist/doc/latex/storecmd
share/texlive/texmf-dist/doc/latex/stringstrings
share/texlive/texmf-dist/doc/latex/struktex
share/texlive/texmf-dist/doc/latex/sttools
share/texlive/texmf-dist/doc/latex/stubs
share/texlive/texmf-dist/doc/latex/studenthandouts
share/texlive/texmf-dist/doc/latex/subdepth
share/texlive/texmf-dist/doc/latex/subeqn
share/texlive/texmf-dist/doc/latex/subeqnarray
share/texlive/texmf-dist/doc/latex/subfig
share/texlive/texmf-dist/doc/latex/subfigmat
share/texlive/texmf-dist/doc/latex/subfigure
share/texlive/texmf-dist/doc/latex/subfiles
share/texlive/texmf-dist/doc/latex/subfloat
share/texlive/texmf-dist/doc/latex/substances
share/texlive/texmf-dist/doc/latex/substitutefont
share/texlive/texmf-dist/doc/latex/substr
share/texlive/texmf-dist/doc/latex/subsupscripts
share/texlive/texmf-dist/doc/latex/sudoku
share/texlive/texmf-dist/doc/latex/sudokubundle
share/texlive/texmf-dist/doc/latex/suftesi
share/texlive/texmf-dist/doc/latex/sugconf
share/texlive/texmf-dist/doc/latex/supertabular
share/texlive/texmf-dist/doc/latex/susy
share/texlive/texmf-dist/doc/latex/svg
share/texlive/texmf-dist/doc/latex/svg-inkscape
share/texlive/texmf-dist/doc/latex/svgcolor
share/texlive/texmf-dist/doc/latex/svn
share/texlive/texmf-dist/doc/latex/svn-multi
share/texlive/texmf-dist/doc/latex/svn-prov
share/texlive/texmf-dist/doc/latex/svninfo
share/texlive/texmf-dist/doc/latex/swebib
share/texlive/texmf-dist/doc/latex/swimgraf
share/texlive/texmf-dist/doc/latex/syllogism
share/texlive/texmf-dist/doc/latex/sympytexpackage
share/texlive/texmf-dist/doc/latex/synproof
share/texlive/texmf-dist/doc/latex/syntax
share/texlive/texmf-dist/doc/latex/syntrace
share/texlive/texmf-dist/doc/latex/synttree
share/texlive/texmf-dist/doc/latex/t-angles
share/texlive/texmf-dist/doc/latex/tabfigures
share/texlive/texmf-dist/doc/latex/table-fct
share/texlive/texmf-dist/doc/latex/tableaux
share/texlive/texmf-dist/doc/latex/tablefootnote
share/texlive/texmf-dist/doc/latex/tableof
share/texlive/texmf-dist/doc/latex/tablestyles
share/texlive/texmf-dist/doc/latex/tablists
share/texlive/texmf-dist/doc/latex/tablor
share/texlive/texmf-dist/doc/latex/tabls
share/texlive/texmf-dist/doc/latex/tabriz-thesis
share/texlive/texmf-dist/doc/latex/tabstackengine
share/texlive/texmf-dist/doc/latex/tabto-ltx
share/texlive/texmf-dist/doc/latex/tabu
share/texlive/texmf-dist/doc/latex/tabularborder
share/texlive/texmf-dist/doc/latex/tabularcalc
share/texlive/texmf-dist/doc/latex/tabularew
share/texlive/texmf-dist/doc/latex/tabulars-e
share/texlive/texmf-dist/doc/latex/tabulary
share/texlive/texmf-dist/doc/latex/tabvar
share/texlive/texmf-dist/doc/latex/tagging
share/texlive/texmf-dist/doc/latex/tagpair
share/texlive/texmf-dist/doc/latex/talk
share/texlive/texmf-dist/doc/latex/tamefloats
share/texlive/texmf-dist/doc/latex/tasks
share/texlive/texmf-dist/doc/latex/tcldoc
share/texlive/texmf-dist/doc/latex/tcolorbox
share/texlive/texmf-dist/doc/latex/tdclock
share/texlive/texmf-dist/doc/latex/tdsfrmath
share/texlive/texmf-dist/doc/latex/technics
share/texlive/texmf-dist/doc/latex/ted
share/texlive/texmf-dist/doc/latex/templates-fenn
share/texlive/texmf-dist/doc/latex/templates-sommer
share/texlive/texmf-dist/doc/latex/templatetools
share/texlive/texmf-dist/doc/latex/tengwarscript
share/texlive/texmf-dist/doc/latex/tensor
share/texlive/texmf-dist/doc/latex/termcal
share/texlive/texmf-dist/doc/latex/termlist
share/texlive/texmf-dist/doc/latex/testhyphens
share/texlive/texmf-dist/doc/latex/testidx
share/texlive/texmf-dist/doc/latex/teubner
share/texlive/texmf-dist/doc/latex/tex-font-errors-cheatsheet
share/texlive/texmf-dist/doc/latex/tex-label
share/texlive/texmf-dist/doc/latex/tex-overview
share/texlive/texmf-dist/doc/latex/texmate
share/texlive/texmf-dist/doc/latex/texments
share/texlive/texmf-dist/doc/latex/texpower
share/texlive/texmf-dist/doc/latex/texproposal
share/texlive/texmf-dist/doc/latex/texshade
share/texlive/texmf-dist/doc/latex/textcase
share/texlive/texmf-dist/doc/latex/textfit
share/texlive/texmf-dist/doc/latex/textglos
share/texlive/texmf-dist/doc/latex/textgreek
share/texlive/texmf-dist/doc/latex/textopo
share/texlive/texmf-dist/doc/latex/textpos
share/texlive/texmf-dist/doc/latex/texvc
share/texlive/texmf-dist/doc/latex/thaienum
share/texlive/texmf-dist/doc/latex/thalie
share/texlive/texmf-dist/doc/latex/theoremref
share/texlive/texmf-dist/doc/latex/thesis-ekf
share/texlive/texmf-dist/doc/latex/thesis-titlepage-fhac
share/texlive/texmf-dist/doc/latex/thinsp
share/texlive/texmf-dist/doc/latex/thmbox
share/texlive/texmf-dist/doc/latex/thmtools
share/texlive/texmf-dist/doc/latex/threadcol
share/texlive/texmf-dist/doc/latex/threeparttable
share/texlive/texmf-dist/doc/latex/threeparttablex
share/texlive/texmf-dist/doc/latex/thumb
share/texlive/texmf-dist/doc/latex/thumbs
share/texlive/texmf-dist/doc/latex/thumby
share/texlive/texmf-dist/doc/latex/thuthesis
share/texlive/texmf-dist/doc/latex/ticket
share/texlive/texmf-dist/doc/latex/ticollege
share/texlive/texmf-dist/doc/latex/tikz-3dplot
share/texlive/texmf-dist/doc/latex/tikz-bayesnet
share/texlive/texmf-dist/doc/latex/tikz-cd
share/texlive/texmf-dist/doc/latex/tikz-dependency
share/texlive/texmf-dist/doc/latex/tikz-dimline
share/texlive/texmf-dist/doc/latex/tikz-feynman
share/texlive/texmf-dist/doc/latex/tikz-inet
share/texlive/texmf-dist/doc/latex/tikz-kalender
share/texlive/texmf-dist/doc/latex/tikz-opm
share/texlive/texmf-dist/doc/latex/tikz-optics
share/texlive/texmf-dist/doc/latex/tikz-page
share/texlive/texmf-dist/doc/latex/tikz-palattice
share/texlive/texmf-dist/doc/latex/tikz-qtree
share/texlive/texmf-dist/doc/latex/tikz-timing
share/texlive/texmf-dist/doc/latex/tikzinclude
share/texlive/texmf-dist/doc/latex/tikzmark
share/texlive/texmf-dist/doc/latex/tikzorbital
share/texlive/texmf-dist/doc/latex/tikzpagenodes
share/texlive/texmf-dist/doc/latex/tikzpeople
share/texlive/texmf-dist/doc/latex/tikzpfeile
share/texlive/texmf-dist/doc/latex/tikzposter
share/texlive/texmf-dist/doc/latex/tikzscale
share/texlive/texmf-dist/doc/latex/tikzsymbols
share/texlive/texmf-dist/doc/latex/timing-diagrams
share/texlive/texmf-dist/doc/latex/tipa-de
share/texlive/texmf-dist/doc/latex/tipfr
share/texlive/texmf-dist/doc/latex/titlecaps
share/texlive/texmf-dist/doc/latex/titlepages
share/texlive/texmf-dist/doc/latex/titlepic
share/texlive/texmf-dist/doc/latex/titleref
share/texlive/texmf-dist/doc/latex/titlesec
share/texlive/texmf-dist/doc/latex/titling
share/texlive/texmf-dist/doc/latex/tkz-base
share/texlive/texmf-dist/doc/latex/tkz-berge
share/texlive/texmf-dist/doc/latex/tkz-doc
share/texlive/texmf-dist/doc/latex/tkz-euclide
share/texlive/texmf-dist/doc/latex/tkz-fct
share/texlive/texmf-dist/doc/latex/tkz-graph
share/texlive/texmf-dist/doc/latex/tkz-kiviat
share/texlive/texmf-dist/doc/latex/tkz-linknodes
share/texlive/texmf-dist/doc/latex/tkz-orm
share/texlive/texmf-dist/doc/latex/tkz-tab
share/texlive/texmf-dist/doc/latex/tlc2
share/texlive/texmf-dist/doc/latex/tocbibind
share/texlive/texmf-dist/doc/latex/tocdata
share/texlive/texmf-dist/doc/latex/tocloft
share/texlive/texmf-dist/doc/latex/tocvsec2
share/texlive/texmf-dist/doc/latex/todo
share/texlive/texmf-dist/doc/latex/todonotes
share/texlive/texmf-dist/doc/latex/tokenizer
share/texlive/texmf-dist/doc/latex/toolbox
share/texlive/texmf-dist/doc/latex/tools
share/texlive/texmf-dist/doc/latex/topfloat
share/texlive/texmf-dist/doc/latex/toptesi
share/texlive/texmf-dist/doc/latex/totcount
share/texlive/texmf-dist/doc/latex/totpages
share/texlive/texmf-dist/doc/latex/tpslifonts
share/texlive/texmf-dist/doc/latex/tqft
share/texlive/texmf-dist/doc/latex/trajan
share/texlive/texmf-dist/doc/latex/tram
share/texlive/texmf-dist/doc/latex/translation-array-fr
share/texlive/texmf-dist/doc/latex/translation-arsclassica-de
share/texlive/texmf-dist/doc/latex/translation-biblatex-de
share/texlive/texmf-dist/doc/latex/translation-chemsym-de
share/texlive/texmf-dist/doc/latex/translation-dcolumn-fr
share/texlive/texmf-dist/doc/latex/translation-ecv-de
share/texlive/texmf-dist/doc/latex/translation-enumitem-de
share/texlive/texmf-dist/doc/latex/translation-europecv-de
share/texlive/texmf-dist/doc/latex/translation-filecontents-de
share/texlive/texmf-dist/doc/latex/translation-moreverb-de
share/texlive/texmf-dist/doc/latex/translation-natbib-fr
share/texlive/texmf-dist/doc/latex/translation-tabbing-fr
share/texlive/texmf-dist/doc/latex/translations
share/texlive/texmf-dist/doc/latex/tree-dvips
share/texlive/texmf-dist/doc/latex/trfsigns
share/texlive/texmf-dist/doc/latex/trimspaces
share/texlive/texmf-dist/doc/latex/trivfloat
share/texlive/texmf-dist/doc/latex/trsym
share/texlive/texmf-dist/doc/latex/truncate
share/texlive/texmf-dist/doc/latex/tucv
share/texlive/texmf-dist/doc/latex/tudscr
share/texlive/texmf-dist/doc/latex/tufte-latex
share/texlive/texmf-dist/doc/latex/tugboat
share/texlive/texmf-dist/doc/latex/tui
share/texlive/texmf-dist/doc/latex/turabian
share/texlive/texmf-dist/doc/latex/turabian-formatting
share/texlive/texmf-dist/doc/latex/turkmen
share/texlive/texmf-dist/doc/latex/turnstile
share/texlive/texmf-dist/doc/latex/turnthepage
share/texlive/texmf-dist/doc/latex/twoinone
share/texlive/texmf-dist/doc/latex/twoup
share/texlive/texmf-dist/doc/latex/txgreeks
share/texlive/texmf-dist/doc/latex/type1cm
share/texlive/texmf-dist/doc/latex/typed-checklist
share/texlive/texmf-dist/doc/latex/typeface
share/texlive/texmf-dist/doc/latex/typehtml
share/texlive/texmf-dist/doc/latex/typoaid
share/texlive/texmf-dist/doc/latex/typogrid
share/texlive/texmf-dist/doc/latex/uaclasses
share/texlive/texmf-dist/doc/latex/uafthesis
share/texlive/texmf-dist/doc/latex/uantwerpendocs
share/texlive/texmf-dist/doc/latex/uassign
share/texlive/texmf-dist/doc/latex/ucbthesis
share/texlive/texmf-dist/doc/latex/ucdavisthesis
share/texlive/texmf-dist/doc/latex/ucharcat
share/texlive/texmf-dist/doc/latex/ucs
share/texlive/texmf-dist/doc/latex/ucthesis
share/texlive/texmf-dist/doc/latex/udesoftec
share/texlive/texmf-dist/doc/latex/uebungsblatt
share/texlive/texmf-dist/doc/latex/uestcthesis
share/texlive/texmf-dist/doc/latex/uhhassignment
share/texlive/texmf-dist/doc/latex/uhrzeit
share/texlive/texmf-dist/doc/latex/uiucredborder
share/texlive/texmf-dist/doc/latex/uiucthesis
share/texlive/texmf-dist/doc/latex/ulqda
share/texlive/texmf-dist/doc/latex/ulthese
share/texlive/texmf-dist/doc/latex/umbclegislation
share/texlive/texmf-dist/doc/latex/umich-thesis
share/texlive/texmf-dist/doc/latex/uml
share/texlive/texmf-dist/doc/latex/umlaute
share/texlive/texmf-dist/doc/latex/umoline
share/texlive/texmf-dist/doc/latex/umthesis
share/texlive/texmf-dist/doc/latex/unamth-template
share/texlive/texmf-dist/doc/latex/unamthesis
share/texlive/texmf-dist/doc/latex/undergradmath
share/texlive/texmf-dist/doc/latex/underlin
share/texlive/texmf-dist/doc/latex/underoverlap
share/texlive/texmf-dist/doc/latex/underscore
share/texlive/texmf-dist/doc/latex/undolabl
share/texlive/texmf-dist/doc/latex/uni-wtal-ger
share/texlive/texmf-dist/doc/latex/uni-wtal-lin
share/texlive/texmf-dist/doc/latex/unicode-math
share/texlive/texmf-dist/doc/latex/units
share/texlive/texmf-dist/doc/latex/unitsdef
share/texlive/texmf-dist/doc/latex/unravel
share/texlive/texmf-dist/doc/latex/unswcover
share/texlive/texmf-dist/doc/latex/uothesis
share/texlive/texmf-dist/doc/latex/uowthesis
share/texlive/texmf-dist/doc/latex/uowthesistitlepage
share/texlive/texmf-dist/doc/latex/upmethodology
share/texlive/texmf-dist/doc/latex/upquote
share/texlive/texmf-dist/doc/latex/urcls
share/texlive/texmf-dist/doc/latex/uri
share/texlive/texmf-dist/doc/latex/url
share/texlive/texmf-dist/doc/latex/usebib
share/texlive/texmf-dist/doc/latex/ushort
share/texlive/texmf-dist/doc/latex/uspace
share/texlive/texmf-dist/doc/latex/uspatent
share/texlive/texmf-dist/doc/latex/ut-thesis
share/texlive/texmf-dist/doc/latex/uwmslide
share/texlive/texmf-dist/doc/latex/uwthesis
share/texlive/texmf-dist/doc/latex/varindex
share/texlive/texmf-dist/doc/latex/varsfromjobname
share/texlive/texmf-dist/doc/latex/varwidth
share/texlive/texmf-dist/doc/latex/vdmlisting
share/texlive/texmf-dist/doc/latex/venndiagram
share/texlive/texmf-dist/doc/latex/verbasef
share/texlive/texmf-dist/doc/latex/verbatimbox
share/texlive/texmf-dist/doc/latex/verbatimcopy
share/texlive/texmf-dist/doc/latex/verbdef
share/texlive/texmf-dist/doc/latex/verbments
share/texlive/texmf-dist/doc/latex/verse
share/texlive/texmf-dist/doc/latex/version
share/texlive/texmf-dist/doc/latex/versions
share/texlive/texmf-dist/doc/latex/versonotes
share/texlive/texmf-dist/doc/latex/vertbars
share/texlive/texmf-dist/doc/latex/vgrid
share/texlive/texmf-dist/doc/latex/vhistory
share/texlive/texmf-dist/doc/latex/visualfaq
share/texlive/texmf-dist/doc/latex/visualpstricks
share/texlive/texmf-dist/doc/latex/visualtikz
share/texlive/texmf-dist/doc/latex/vmargin
share/texlive/texmf-dist/doc/latex/vocaltract
share/texlive/texmf-dist/doc/latex/volumes
share/texlive/texmf-dist/doc/latex/voss-mathcol
share/texlive/texmf-dist/doc/latex/vpe
share/texlive/texmf-dist/doc/latex/vruler
share/texlive/texmf-dist/doc/latex/vwcol
share/texlive/texmf-dist/doc/latex/wallpaper
share/texlive/texmf-dist/doc/latex/warning
share/texlive/texmf-dist/doc/latex/warpcol
share/texlive/texmf-dist/doc/latex/was
share/texlive/texmf-dist/doc/latex/wasysym
share/texlive/texmf-dist/doc/latex/webguide
share/texlive/texmf-dist/doc/latex/widetable
share/texlive/texmf-dist/doc/latex/williams
share/texlive/texmf-dist/doc/latex/withargs
share/texlive/texmf-dist/doc/latex/wnri-latex
share/texlive/texmf-dist/doc/latex/wordcount
share/texlive/texmf-dist/doc/latex/wordlike
share/texlive/texmf-dist/doc/latex/wrapfig
share/texlive/texmf-dist/doc/latex/wsemclassic
share/texlive/texmf-dist/doc/latex/wtref
share/texlive/texmf-dist/doc/latex/xargs
share/texlive/texmf-dist/doc/latex/xassoccnt
share/texlive/texmf-dist/doc/latex/xcite
share/texlive/texmf-dist/doc/latex/xcjk2uni
share/texlive/texmf-dist/doc/latex/xcntperchap
share/texlive/texmf-dist/doc/latex/xcolor
share/texlive/texmf-dist/doc/latex/xcolor-material
share/texlive/texmf-dist/doc/latex/xcolor-solarized
share/texlive/texmf-dist/doc/latex/xcookybooky
share/texlive/texmf-dist/doc/latex/xdoc
share/texlive/texmf-dist/doc/latex/xduthesis
share/texlive/texmf-dist/doc/latex/xebaposter
share/texlive/texmf-dist/doc/latex/xellipsis
share/texlive/texmf-dist/doc/latex/xfor
share/texlive/texmf-dist/doc/latex/xhfill
share/texlive/texmf-dist/doc/latex/xifthen
share/texlive/texmf-dist/doc/latex/xkeyval
share/texlive/texmf-dist/doc/latex/xltxtra
share/texlive/texmf-dist/doc/latex/xmpincl
share/texlive/texmf-dist/doc/latex/xnewcommand
share/texlive/texmf-dist/doc/latex/xoptarg
share/texlive/texmf-dist/doc/latex/xpatch
share/texlive/texmf-dist/doc/latex/xpeek
share/texlive/texmf-dist/doc/latex/xpiano
share/texlive/texmf-dist/doc/latex/xpicture
share/texlive/texmf-dist/doc/latex/xpinyin
share/texlive/texmf-dist/doc/latex/xprintlen
share/texlive/texmf-dist/doc/latex/xpunctuate
share/texlive/texmf-dist/doc/latex/xsavebox
share/texlive/texmf-dist/doc/latex/xsim
share/texlive/texmf-dist/doc/latex/xskak
share/texlive/texmf-dist/doc/latex/xtab
share/texlive/texmf-dist/doc/latex/xwatermark
share/texlive/texmf-dist/doc/latex/xyling
share/texlive/texmf-dist/doc/latex/xymtex
share/texlive/texmf-dist/doc/latex/xytree
share/texlive/texmf-dist/doc/latex/yafoot
share/texlive/texmf-dist/doc/latex/yagusylo
share/texlive/texmf-dist/doc/latex/yaletter
share/texlive/texmf-dist/doc/latex/yathesis
share/texlive/texmf-dist/doc/latex/ycbook
share/texlive/texmf-dist/doc/latex/ydoc
share/texlive/texmf-dist/doc/latex/yfonts
share/texlive/texmf-dist/doc/latex/york-thesis
share/texlive/texmf-dist/doc/latex/youngtab
share/texlive/texmf-dist/doc/latex/yplan
share/texlive/texmf-dist/doc/latex/ytableau
share/texlive/texmf-dist/doc/latex/zed-csp
share/texlive/texmf-dist/doc/latex/zhnumber
share/texlive/texmf-dist/doc/latex/ziffer
share/texlive/texmf-dist/doc/latex/zwgetfdate
share/texlive/texmf-dist/doc/latex/zwpagelayout
share/texlive/texmf-dist/doc/latex/zxjafbfont
share/texlive/texmf-dist/doc/latex/zxjafont
share/texlive/texmf-dist/doc/latex/zxjatype"
