TERMUX_SUBPKG_DESCRIPTION="Documentation for the latex packages of TeX Live. Contains docs for latex packages starting with a-k."
TERMUX_SUBPKG_DEPENDS="texlive-full"
TERMUX_SUBPKG_INCLUDE="share/texlive/texmf-dist/doc/latex/12many
share/texlive/texmf-dist/doc/latex/ESIEEcv
share/texlive/texmf-dist/doc/latex/GS1
share/texlive/texmf-dist/doc/latex/HA-prosper
share/texlive/texmf-dist/doc/latex/IEEEconf
share/texlive/texmf-dist/doc/latex/IEEEtran
share/texlive/texmf-dist/doc/latex/MemoirChapStyles
share/texlive/texmf-dist/doc/latex/SIstyle
share/texlive/texmf-dist/doc/latex/SIunits
share/texlive/texmf-dist/doc/latex/Tabbing
share/texlive/texmf-dist/doc/latex/a0poster
share/texlive/texmf-dist/doc/latex/a4wide
share/texlive/texmf-dist/doc/latex/a5comb
share/texlive/texmf-dist/doc/latex/aastex
share/texlive/texmf-dist/doc/latex/abc
share/texlive/texmf-dist/doc/latex/abntex2
share/texlive/texmf-dist/doc/latex/abraces
share/texlive/texmf-dist/doc/latex/abstract
share/texlive/texmf-dist/doc/latex/achemso
share/texlive/texmf-dist/doc/latex/acmart
share/texlive/texmf-dist/doc/latex/acmconf
share/texlive/texmf-dist/doc/latex/acro
share/texlive/texmf-dist/doc/latex/acronym
share/texlive/texmf-dist/doc/latex/acroterm
share/texlive/texmf-dist/doc/latex/active-conf
share/texlive/texmf-dist/doc/latex/actuarialangle
share/texlive/texmf-dist/doc/latex/actuarialsymbol
share/texlive/texmf-dist/doc/latex/addfont
share/texlive/texmf-dist/doc/latex/addlines
share/texlive/texmf-dist/doc/latex/adfathesis
share/texlive/texmf-dist/doc/latex/adjmulticol
share/texlive/texmf-dist/doc/latex/adjustbox
share/texlive/texmf-dist/doc/latex/adrconv
share/texlive/texmf-dist/doc/latex/adtrees
share/texlive/texmf-dist/doc/latex/advdate
share/texlive/texmf-dist/doc/latex/aeguill
share/texlive/texmf-dist/doc/latex/afparticle
share/texlive/texmf-dist/doc/latex/afthesis
share/texlive/texmf-dist/doc/latex/aguplus
share/texlive/texmf-dist/doc/latex/aiaa
share/texlive/texmf-dist/doc/latex/akktex
share/texlive/texmf-dist/doc/latex/akletter
share/texlive/texmf-dist/doc/latex/alertmessage
share/texlive/texmf-dist/doc/latex/alg
share/texlive/texmf-dist/doc/latex/algorithm2e
share/texlive/texmf-dist/doc/latex/algorithmicx
share/texlive/texmf-dist/doc/latex/algorithms
share/texlive/texmf-dist/doc/latex/alnumsec
share/texlive/texmf-dist/doc/latex/alterqcm
share/texlive/texmf-dist/doc/latex/altfont
share/texlive/texmf-dist/doc/latex/ametsoc
share/texlive/texmf-dist/doc/latex/amsaddr
share/texlive/texmf-dist/doc/latex/amscls
share/texlive/texmf-dist/doc/latex/amslatex-primer
share/texlive/texmf-dist/doc/latex/amsldoc-it
share/texlive/texmf-dist/doc/latex/amsldoc-vn
share/texlive/texmf-dist/doc/latex/amsmath
share/texlive/texmf-dist/doc/latex/amsmath-it
share/texlive/texmf-dist/doc/latex/amsrefs
share/texlive/texmf-dist/doc/latex/amsthdoc-it
share/texlive/texmf-dist/doc/latex/animate
share/texlive/texmf-dist/doc/latex/anonchap
share/texlive/texmf-dist/doc/latex/answers
share/texlive/texmf-dist/doc/latex/antt
share/texlive/texmf-dist/doc/latex/anufinalexam
share/texlive/texmf-dist/doc/latex/anyfontsize
share/texlive/texmf-dist/doc/latex/anysize
share/texlive/texmf-dist/doc/latex/aobs-tikz
share/texlive/texmf-dist/doc/latex/aomart
share/texlive/texmf-dist/doc/latex/apa
share/texlive/texmf-dist/doc/latex/apa6
share/texlive/texmf-dist/doc/latex/apa6e
share/texlive/texmf-dist/doc/latex/appendix
share/texlive/texmf-dist/doc/latex/appendixnumberbeamer
share/texlive/texmf-dist/doc/latex/apprends-latex
share/texlive/texmf-dist/doc/latex/apptools
share/texlive/texmf-dist/doc/latex/apxproof
share/texlive/texmf-dist/doc/latex/arabi
share/texlive/texmf-dist/doc/latex/arabi-add
share/texlive/texmf-dist/doc/latex/arabtex
share/texlive/texmf-dist/doc/latex/aramaic-serto
share/texlive/texmf-dist/doc/latex/archaeologie
share/texlive/texmf-dist/doc/latex/arcs
share/texlive/texmf-dist/doc/latex/arraysort
share/texlive/texmf-dist/doc/latex/arsclassica
share/texlive/texmf-dist/doc/latex/articleingud
share/texlive/texmf-dist/doc/latex/arydshln
share/texlive/texmf-dist/doc/latex/asaetr
share/texlive/texmf-dist/doc/latex/ascelike
share/texlive/texmf-dist/doc/latex/asciilist
share/texlive/texmf-dist/doc/latex/askmaps
share/texlive/texmf-dist/doc/latex/aspectratio
share/texlive/texmf-dist/doc/latex/assignment
share/texlive/texmf-dist/doc/latex/assoccnt
share/texlive/texmf-dist/doc/latex/asyfig
share/texlive/texmf-dist/doc/latex/asypictureb
share/texlive/texmf-dist/doc/latex/attachfile
share/texlive/texmf-dist/doc/latex/aucklandthesis
share/texlive/texmf-dist/doc/latex/augie
share/texlive/texmf-dist/doc/latex/aurical
share/texlive/texmf-dist/doc/latex/aurl
share/texlive/texmf-dist/doc/latex/authoraftertitle
share/texlive/texmf-dist/doc/latex/authorindex
share/texlive/texmf-dist/doc/latex/auto-pst-pdf
share/texlive/texmf-dist/doc/latex/autoarea
share/texlive/texmf-dist/doc/latex/autobreak
share/texlive/texmf-dist/doc/latex/autonum
share/texlive/texmf-dist/doc/latex/autopdf
share/texlive/texmf-dist/doc/latex/avremu
share/texlive/texmf-dist/doc/latex/awesomebox
share/texlive/texmf-dist/doc/latex/axodraw2
share/texlive/texmf-dist/doc/latex/b1encoding
share/texlive/texmf-dist/doc/latex/babel
share/texlive/texmf-dist/doc/latex/background
share/texlive/texmf-dist/doc/latex/backnaur
share/texlive/texmf-dist/doc/latex/bangorcsthesis
share/texlive/texmf-dist/doc/latex/bangorexam
share/texlive/texmf-dist/doc/latex/bangtex
share/texlive/texmf-dist/doc/latex/bankstatement
share/texlive/texmf-dist/doc/latex/barcodes
share/texlive/texmf-dist/doc/latex/bardiag
share/texlive/texmf-dist/doc/latex/base
share/texlive/texmf-dist/doc/latex/bashful
share/texlive/texmf-dist/doc/latex/basicarith
share/texlive/texmf-dist/doc/latex/basque-book
share/texlive/texmf-dist/doc/latex/basque-date
share/texlive/texmf-dist/doc/latex/bbding
share/texlive/texmf-dist/doc/latex/bbm-macros
share/texlive/texmf-dist/doc/latex/bbold
share/texlive/texmf-dist/doc/latex/bchart
share/texlive/texmf-dist/doc/latex/bclogo
share/texlive/texmf-dist/doc/latex/beamer
share/texlive/texmf-dist/doc/latex/beamer-FUBerlin
share/texlive/texmf-dist/doc/latex/beamer-tut-pt
share/texlive/texmf-dist/doc/latex/beamer-verona
share/texlive/texmf-dist/doc/latex/beamer2thesis
share/texlive/texmf-dist/doc/latex/beameraudience
share/texlive/texmf-dist/doc/latex/beamercolorthemeowl
share/texlive/texmf-dist/doc/latex/beamerdarkthemes
share/texlive/texmf-dist/doc/latex/beamerposter
share/texlive/texmf-dist/doc/latex/beamersubframe
share/texlive/texmf-dist/doc/latex/beamerswitch
share/texlive/texmf-dist/doc/latex/beamertheme-cuerna
share/texlive/texmf-dist/doc/latex/beamertheme-detlevcm
share/texlive/texmf-dist/doc/latex/beamertheme-epyt
share/texlive/texmf-dist/doc/latex/beamertheme-metropolis
share/texlive/texmf-dist/doc/latex/beamertheme-phnompenh
share/texlive/texmf-dist/doc/latex/beamertheme-upenn-bc
share/texlive/texmf-dist/doc/latex/beamerthemenirma
share/texlive/texmf-dist/doc/latex/begingreek
share/texlive/texmf-dist/doc/latex/begriff
share/texlive/texmf-dist/doc/latex/betababel
share/texlive/texmf-dist/doc/latex/beton
share/texlive/texmf-dist/doc/latex/bewerbung
share/texlive/texmf-dist/doc/latex/bez123
share/texlive/texmf-dist/doc/latex/bezos
share/texlive/texmf-dist/doc/latex/bgreek
share/texlive/texmf-dist/doc/latex/bgteubner
share/texlive/texmf-dist/doc/latex/bhcexam
share/texlive/texmf-dist/doc/latex/bibarts
share/texlive/texmf-dist/doc/latex/biblatex
share/texlive/texmf-dist/doc/latex/biblatex-abnt
share/texlive/texmf-dist/doc/latex/biblatex-anonymous
share/texlive/texmf-dist/doc/latex/biblatex-apa
share/texlive/texmf-dist/doc/latex/biblatex-archaeology
share/texlive/texmf-dist/doc/latex/biblatex-arthistory-bonn
share/texlive/texmf-dist/doc/latex/biblatex-bookinarticle
share/texlive/texmf-dist/doc/latex/biblatex-bookinother
share/texlive/texmf-dist/doc/latex/biblatex-bwl
share/texlive/texmf-dist/doc/latex/biblatex-caspervector
share/texlive/texmf-dist/doc/latex/biblatex-cheatsheet
share/texlive/texmf-dist/doc/latex/biblatex-chem
share/texlive/texmf-dist/doc/latex/biblatex-chicago
share/texlive/texmf-dist/doc/latex/biblatex-claves
share/texlive/texmf-dist/doc/latex/biblatex-dw
share/texlive/texmf-dist/doc/latex/biblatex-fiwi
share/texlive/texmf-dist/doc/latex/biblatex-gb7714-2015
share/texlive/texmf-dist/doc/latex/biblatex-gost
share/texlive/texmf-dist/doc/latex/biblatex-historian
share/texlive/texmf-dist/doc/latex/biblatex-ieee
share/texlive/texmf-dist/doc/latex/biblatex-ijsra
share/texlive/texmf-dist/doc/latex/biblatex-iso690
share/texlive/texmf-dist/doc/latex/biblatex-juradiss
share/texlive/texmf-dist/doc/latex/biblatex-lni
share/texlive/texmf-dist/doc/latex/biblatex-luh-ipw
share/texlive/texmf-dist/doc/latex/biblatex-manuscripts-philology
share/texlive/texmf-dist/doc/latex/biblatex-mla
share/texlive/texmf-dist/doc/latex/biblatex-morenames
share/texlive/texmf-dist/doc/latex/biblatex-multiple-dm
share/texlive/texmf-dist/doc/latex/biblatex-musuos
share/texlive/texmf-dist/doc/latex/biblatex-nature
share/texlive/texmf-dist/doc/latex/biblatex-nejm
share/texlive/texmf-dist/doc/latex/biblatex-nottsclassic
share/texlive/texmf-dist/doc/latex/biblatex-opcit-booktitle
share/texlive/texmf-dist/doc/latex/biblatex-oxref
share/texlive/texmf-dist/doc/latex/biblatex-philosophy
share/texlive/texmf-dist/doc/latex/biblatex-phys
share/texlive/texmf-dist/doc/latex/biblatex-publist
share/texlive/texmf-dist/doc/latex/biblatex-realauthor
share/texlive/texmf-dist/doc/latex/biblatex-sbl
share/texlive/texmf-dist/doc/latex/biblatex-science
share/texlive/texmf-dist/doc/latex/biblatex-shortfields
share/texlive/texmf-dist/doc/latex/biblatex-source-division
share/texlive/texmf-dist/doc/latex/biblatex-subseries
share/texlive/texmf-dist/doc/latex/biblatex-swiss-legal
share/texlive/texmf-dist/doc/latex/biblatex-trad
share/texlive/texmf-dist/doc/latex/biblatex-true-citepages-omit
share/texlive/texmf-dist/doc/latex/bibleref
share/texlive/texmf-dist/doc/latex/bibleref-french
share/texlive/texmf-dist/doc/latex/bibleref-german
share/texlive/texmf-dist/doc/latex/bibleref-lds
share/texlive/texmf-dist/doc/latex/bibleref-mouth
share/texlive/texmf-dist/doc/latex/bibleref-parse
share/texlive/texmf-dist/doc/latex/bibletext
share/texlive/texmf-dist/doc/latex/biblist
share/texlive/texmf-dist/doc/latex/bibtopic
share/texlive/texmf-dist/doc/latex/bibtopicprefix
share/texlive/texmf-dist/doc/latex/bibunits
share/texlive/texmf-dist/doc/latex/bigfoot
share/texlive/texmf-dist/doc/latex/bigints
share/texlive/texmf-dist/doc/latex/binarytree
share/texlive/texmf-dist/doc/latex/binomexp
share/texlive/texmf-dist/doc/latex/biochemistry-colors
share/texlive/texmf-dist/doc/latex/biocon
share/texlive/texmf-dist/doc/latex/bitpattern
share/texlive/texmf-dist/doc/latex/bizcard
share/texlive/texmf-dist/doc/latex/blindtext
share/texlive/texmf-dist/doc/latex/blkarray
share/texlive/texmf-dist/doc/latex/blochsphere
share/texlive/texmf-dist/doc/latex/block
share/texlive/texmf-dist/doc/latex/bloques
share/texlive/texmf-dist/doc/latex/blox
share/texlive/texmf-dist/doc/latex/bnumexpr
share/texlive/texmf-dist/doc/latex/bodegraph
share/texlive/texmf-dist/doc/latex/bohr
share/texlive/texmf-dist/doc/latex/boites
share/texlive/texmf-dist/doc/latex/bold-extra
share/texlive/texmf-dist/doc/latex/boldtensors
share/texlive/texmf-dist/doc/latex/bondgraph
share/texlive/texmf-dist/doc/latex/bondgraphs
share/texlive/texmf-dist/doc/latex/bookcover
share/texlive/texmf-dist/doc/latex/bookest
share/texlive/texmf-dist/doc/latex/booklet
share/texlive/texmf-dist/doc/latex/booktabs
share/texlive/texmf-dist/doc/latex/booktabs-de
share/texlive/texmf-dist/doc/latex/booktabs-fr
share/texlive/texmf-dist/doc/latex/boolexpr
share/texlive/texmf-dist/doc/latex/bophook
share/texlive/texmf-dist/doc/latex/bosisio
share/texlive/texmf-dist/doc/latex/boxedminipage
share/texlive/texmf-dist/doc/latex/boxedminipage2e
share/texlive/texmf-dist/doc/latex/boxhandler
share/texlive/texmf-dist/doc/latex/bpchem
share/texlive/texmf-dist/doc/latex/br-lex
share/texlive/texmf-dist/doc/latex/bracketkey
share/texlive/texmf-dist/doc/latex/braids
share/texlive/texmf-dist/doc/latex/braille
share/texlive/texmf-dist/doc/latex/braket
share/texlive/texmf-dist/doc/latex/brandeis-dissertation
share/texlive/texmf-dist/doc/latex/breakcites
share/texlive/texmf-dist/doc/latex/breakurl
share/texlive/texmf-dist/doc/latex/bredzenie
share/texlive/texmf-dist/doc/latex/breqn
share/texlive/texmf-dist/doc/latex/bropd
share/texlive/texmf-dist/doc/latex/bullcntr
share/texlive/texmf-dist/doc/latex/bussproofs
share/texlive/texmf-dist/doc/latex/bxbase
share/texlive/texmf-dist/doc/latex/bxcjkjatype
share/texlive/texmf-dist/doc/latex/bxdpx-beamer
share/texlive/texmf-dist/doc/latex/bxdvidriver
share/texlive/texmf-dist/doc/latex/bxeepic
share/texlive/texmf-dist/doc/latex/bxenclose
share/texlive/texmf-dist/doc/latex/bxjalipsum
share/texlive/texmf-dist/doc/latex/bxjscls
share/texlive/texmf-dist/doc/latex/bxnewfont
share/texlive/texmf-dist/doc/latex/bxorigcapt
share/texlive/texmf-dist/doc/latex/bxpapersize
share/texlive/texmf-dist/doc/latex/bxpdfver
share/texlive/texmf-dist/doc/latex/bytefield
share/texlive/texmf-dist/doc/latex/cachepic
share/texlive/texmf-dist/doc/latex/calcage
share/texlive/texmf-dist/doc/latex/calctab
share/texlive/texmf-dist/doc/latex/calculation
share/texlive/texmf-dist/doc/latex/calculator
share/texlive/texmf-dist/doc/latex/calligra
share/texlive/texmf-dist/doc/latex/callouts
share/texlive/texmf-dist/doc/latex/calrsfs
share/texlive/texmf-dist/doc/latex/cals
share/texlive/texmf-dist/doc/latex/calxxxx-yyyy
share/texlive/texmf-dist/doc/latex/cancel
share/texlive/texmf-dist/doc/latex/canoniclayout
share/texlive/texmf-dist/doc/latex/capt-of
share/texlive/texmf-dist/doc/latex/captcont
share/texlive/texmf-dist/doc/latex/captdef
share/texlive/texmf-dist/doc/latex/caption
share/texlive/texmf-dist/doc/latex/carbohydrates
share/texlive/texmf-dist/doc/latex/carlisle
share/texlive/texmf-dist/doc/latex/cascadilla
share/texlive/texmf-dist/doc/latex/cases
share/texlive/texmf-dist/doc/latex/casyl
share/texlive/texmf-dist/doc/latex/catchfilebetweentags
share/texlive/texmf-dist/doc/latex/catechis
share/texlive/texmf-dist/doc/latex/catoptions
share/texlive/texmf-dist/doc/latex/cbcoptic
share/texlive/texmf-dist/doc/latex/ccaption
share/texlive/texmf-dist/doc/latex/ccfonts
share/texlive/texmf-dist/doc/latex/ccicons
share/texlive/texmf-dist/doc/latex/cclicenses
share/texlive/texmf-dist/doc/latex/cd
share/texlive/texmf-dist/doc/latex/cd-cover
share/texlive/texmf-dist/doc/latex/cdpbundl
share/texlive/texmf-dist/doc/latex/cell
share/texlive/texmf-dist/doc/latex/cellspace
share/texlive/texmf-dist/doc/latex/celtic
share/texlive/texmf-dist/doc/latex/censor
share/texlive/texmf-dist/doc/latex/cfr-initials
share/texlive/texmf-dist/doc/latex/changebar
share/texlive/texmf-dist/doc/latex/changelayout
share/texlive/texmf-dist/doc/latex/changepage
share/texlive/texmf-dist/doc/latex/changes
share/texlive/texmf-dist/doc/latex/chappg
share/texlive/texmf-dist/doc/latex/chapterfolder
share/texlive/texmf-dist/doc/latex/chbibref
share/texlive/texmf-dist/doc/latex/checklistings
share/texlive/texmf-dist/doc/latex/chembst
share/texlive/texmf-dist/doc/latex/chemcompounds
share/texlive/texmf-dist/doc/latex/chemcono
share/texlive/texmf-dist/doc/latex/chemexec
share/texlive/texmf-dist/doc/latex/chemformula
share/texlive/texmf-dist/doc/latex/chemgreek
share/texlive/texmf-dist/doc/latex/chemmacros
share/texlive/texmf-dist/doc/latex/chemnum
share/texlive/texmf-dist/doc/latex/chemschemex
share/texlive/texmf-dist/doc/latex/chemstyle
share/texlive/texmf-dist/doc/latex/chess-problem-diagrams
share/texlive/texmf-dist/doc/latex/chessboard
share/texlive/texmf-dist/doc/latex/chessfss
share/texlive/texmf-dist/doc/latex/chet
share/texlive/texmf-dist/doc/latex/chextras
share/texlive/texmf-dist/doc/latex/childdoc
share/texlive/texmf-dist/doc/latex/chkfloat
share/texlive/texmf-dist/doc/latex/chletter
share/texlive/texmf-dist/doc/latex/chngcntr
share/texlive/texmf-dist/doc/latex/chronology
share/texlive/texmf-dist/doc/latex/chscite
share/texlive/texmf-dist/doc/latex/churchslavonic
share/texlive/texmf-dist/doc/latex/circ
share/texlive/texmf-dist/doc/latex/circuitikz
share/texlive/texmf-dist/doc/latex/cite
share/texlive/texmf-dist/doc/latex/citeall
share/texlive/texmf-dist/doc/latex/cjhebrew
share/texlive/texmf-dist/doc/latex/cjk
share/texlive/texmf-dist/doc/latex/cjk-ko
share/texlive/texmf-dist/doc/latex/cjkpunct
share/texlive/texmf-dist/doc/latex/classics
share/texlive/texmf-dist/doc/latex/classicthesis
share/texlive/texmf-dist/doc/latex/cleanthesis
share/texlive/texmf-dist/doc/latex/clefval
share/texlive/texmf-dist/doc/latex/cleveref
share/texlive/texmf-dist/doc/latex/clipboard
share/texlive/texmf-dist/doc/latex/clock
share/texlive/texmf-dist/doc/latex/clrscode
share/texlive/texmf-dist/doc/latex/clrscode3e
share/texlive/texmf-dist/doc/latex/cmap
share/texlive/texmf-dist/doc/latex/cmbright
share/texlive/texmf-dist/doc/latex/cmdstring
share/texlive/texmf-dist/doc/latex/cmdtrack
share/texlive/texmf-dist/doc/latex/cmpica
share/texlive/texmf-dist/doc/latex/cmpj
share/texlive/texmf-dist/doc/latex/cmsd
share/texlive/texmf-dist/doc/latex/cmtiup
share/texlive/texmf-dist/doc/latex/cnbwp
share/texlive/texmf-dist/doc/latex/cnltx
share/texlive/texmf-dist/doc/latex/cntformats
share/texlive/texmf-dist/doc/latex/cntperchap
share/texlive/texmf-dist/doc/latex/codedoc
share/texlive/texmf-dist/doc/latex/codepage
share/texlive/texmf-dist/doc/latex/codesection
share/texlive/texmf-dist/doc/latex/codicefiscaleitaliano
share/texlive/texmf-dist/doc/latex/collcell
share/texlive/texmf-dist/doc/latex/collectbox
share/texlive/texmf-dist/doc/latex/collref
share/texlive/texmf-dist/doc/latex/colordoc
share/texlive/texmf-dist/doc/latex/colorinfo
share/texlive/texmf-dist/doc/latex/coloring
share/texlive/texmf-dist/doc/latex/colorspace
share/texlive/texmf-dist/doc/latex/colortbl
share/texlive/texmf-dist/doc/latex/colorwav
share/texlive/texmf-dist/doc/latex/colorweb
share/texlive/texmf-dist/doc/latex/colourchange
share/texlive/texmf-dist/doc/latex/combelow
share/texlive/texmf-dist/doc/latex/combine
share/texlive/texmf-dist/doc/latex/combinedgraphics
share/texlive/texmf-dist/doc/latex/comicneue
share/texlive/texmf-dist/doc/latex/comma
share/texlive/texmf-dist/doc/latex/commath
share/texlive/texmf-dist/doc/latex/comment
share/texlive/texmf-dist/doc/latex/complexity
share/texlive/texmf-dist/doc/latex/comprehensive
share/texlive/texmf-dist/doc/latex/computational-complexity
share/texlive/texmf-dist/doc/latex/concepts
share/texlive/texmf-dist/doc/latex/concprog
share/texlive/texmf-dist/doc/latex/confproc
share/texlive/texmf-dist/doc/latex/constants
share/texlive/texmf-dist/doc/latex/conteq
share/texlive/texmf-dist/doc/latex/continue
share/texlive/texmf-dist/doc/latex/contour
share/texlive/texmf-dist/doc/latex/contracard
share/texlive/texmf-dist/doc/latex/conv-xkv
share/texlive/texmf-dist/doc/latex/cooking
share/texlive/texmf-dist/doc/latex/cooking-units
share/texlive/texmf-dist/doc/latex/cookingsymbols
share/texlive/texmf-dist/doc/latex/cool
share/texlive/texmf-dist/doc/latex/coollist
share/texlive/texmf-dist/doc/latex/coolstr
share/texlive/texmf-dist/doc/latex/coolthms
share/texlive/texmf-dist/doc/latex/cooltooltips
share/texlive/texmf-dist/doc/latex/coordsys
share/texlive/texmf-dist/doc/latex/copyedit
share/texlive/texmf-dist/doc/latex/copyrightbox
share/texlive/texmf-dist/doc/latex/correctmathalign
share/texlive/texmf-dist/doc/latex/coseoul
share/texlive/texmf-dist/doc/latex/counttexruns
share/texlive/texmf-dist/doc/latex/courseoutline
share/texlive/texmf-dist/doc/latex/coursepaper
share/texlive/texmf-dist/doc/latex/coverpage
share/texlive/texmf-dist/doc/latex/covington
share/texlive/texmf-dist/doc/latex/cprotect
share/texlive/texmf-dist/doc/latex/cquthesis
share/texlive/texmf-dist/doc/latex/crbox
share/texlive/texmf-dist/doc/latex/crop
share/texlive/texmf-dist/doc/latex/crossreference
share/texlive/texmf-dist/doc/latex/crossword
share/texlive/texmf-dist/doc/latex/crosswrd
share/texlive/texmf-dist/doc/latex/cryptocode
share/texlive/texmf-dist/doc/latex/cryst
share/texlive/texmf-dist/doc/latex/csbulletin
share/texlive/texmf-dist/doc/latex/csquotes
share/texlive/texmf-dist/doc/latex/csquotes-de
share/texlive/texmf-dist/doc/latex/css-colors
share/texlive/texmf-dist/doc/latex/csvsimple
share/texlive/texmf-dist/doc/latex/ctable
share/texlive/texmf-dist/doc/latex/ctanify
share/texlive/texmf-dist/doc/latex/ctex
share/texlive/texmf-dist/doc/latex/ctex-faq
share/texlive/texmf-dist/doc/latex/ctib
share/texlive/texmf-dist/doc/latex/cuisine
share/texlive/texmf-dist/doc/latex/currfile
share/texlive/texmf-dist/doc/latex/currvita
share/texlive/texmf-dist/doc/latex/cursolatex
share/texlive/texmf-dist/doc/latex/curve
share/texlive/texmf-dist/doc/latex/curve2e
share/texlive/texmf-dist/doc/latex/curves
share/texlive/texmf-dist/doc/latex/custom-bib
share/texlive/texmf-dist/doc/latex/cutwin
share/texlive/texmf-dist/doc/latex/cv
share/texlive/texmf-dist/doc/latex/cv4tw
share/texlive/texmf-dist/doc/latex/cweb-latex
share/texlive/texmf-dist/doc/latex/cyber
share/texlive/texmf-dist/doc/latex/cybercic
share/texlive/texmf-dist/doc/latex/cyrillic
share/texlive/texmf-dist/doc/latex/dashbox
share/texlive/texmf-dist/doc/latex/dashrule
share/texlive/texmf-dist/doc/latex/dashundergaps
share/texlive/texmf-dist/doc/latex/dataref
share/texlive/texmf-dist/doc/latex/datatool
share/texlive/texmf-dist/doc/latex/dateiliste
share/texlive/texmf-dist/doc/latex/datenumber
share/texlive/texmf-dist/doc/latex/datetime
share/texlive/texmf-dist/doc/latex/datetime2
share/texlive/texmf-dist/doc/latex/datetime2-bahasai
share/texlive/texmf-dist/doc/latex/datetime2-basque
share/texlive/texmf-dist/doc/latex/datetime2-breton
share/texlive/texmf-dist/doc/latex/datetime2-bulgarian
share/texlive/texmf-dist/doc/latex/datetime2-catalan
share/texlive/texmf-dist/doc/latex/datetime2-croatian
share/texlive/texmf-dist/doc/latex/datetime2-czech
share/texlive/texmf-dist/doc/latex/datetime2-danish
share/texlive/texmf-dist/doc/latex/datetime2-dutch
share/texlive/texmf-dist/doc/latex/datetime2-en-fulltext
share/texlive/texmf-dist/doc/latex/datetime2-english
share/texlive/texmf-dist/doc/latex/datetime2-esperanto
share/texlive/texmf-dist/doc/latex/datetime2-estonian
share/texlive/texmf-dist/doc/latex/datetime2-finnish
share/texlive/texmf-dist/doc/latex/datetime2-french
share/texlive/texmf-dist/doc/latex/datetime2-galician
share/texlive/texmf-dist/doc/latex/datetime2-german
share/texlive/texmf-dist/doc/latex/datetime2-greek
share/texlive/texmf-dist/doc/latex/datetime2-hebrew
share/texlive/texmf-dist/doc/latex/datetime2-icelandic
share/texlive/texmf-dist/doc/latex/datetime2-irish
share/texlive/texmf-dist/doc/latex/datetime2-it-fulltext
share/texlive/texmf-dist/doc/latex/datetime2-italian
share/texlive/texmf-dist/doc/latex/datetime2-latin
share/texlive/texmf-dist/doc/latex/datetime2-lsorbian
share/texlive/texmf-dist/doc/latex/datetime2-magyar
share/texlive/texmf-dist/doc/latex/datetime2-norsk
share/texlive/texmf-dist/doc/latex/datetime2-polish
share/texlive/texmf-dist/doc/latex/datetime2-portuges
share/texlive/texmf-dist/doc/latex/datetime2-romanian
share/texlive/texmf-dist/doc/latex/datetime2-russian
share/texlive/texmf-dist/doc/latex/datetime2-samin
share/texlive/texmf-dist/doc/latex/datetime2-scottish
share/texlive/texmf-dist/doc/latex/datetime2-serbian
share/texlive/texmf-dist/doc/latex/datetime2-slovak
share/texlive/texmf-dist/doc/latex/datetime2-slovene
share/texlive/texmf-dist/doc/latex/datetime2-spanish
share/texlive/texmf-dist/doc/latex/datetime2-swedish
share/texlive/texmf-dist/doc/latex/datetime2-turkish
share/texlive/texmf-dist/doc/latex/datetime2-ukrainian
share/texlive/texmf-dist/doc/latex/datetime2-usorbian
share/texlive/texmf-dist/doc/latex/datetime2-welsh
share/texlive/texmf-dist/doc/latex/dblfloatfix
share/texlive/texmf-dist/doc/latex/dccpaper
share/texlive/texmf-dist/doc/latex/decimal
share/texlive/texmf-dist/doc/latex/decorule
share/texlive/texmf-dist/doc/latex/delim
share/texlive/texmf-dist/doc/latex/delimseasy
share/texlive/texmf-dist/doc/latex/delimset
share/texlive/texmf-dist/doc/latex/delimtxt
share/texlive/texmf-dist/doc/latex/denisbdoc
share/texlive/texmf-dist/doc/latex/dhua
share/texlive/texmf-dist/doc/latex/diadia
share/texlive/texmf-dist/doc/latex/diagbox
share/texlive/texmf-dist/doc/latex/diagmac2
share/texlive/texmf-dist/doc/latex/diagnose
share/texlive/texmf-dist/doc/latex/dialogl
share/texlive/texmf-dist/doc/latex/dichokey
share/texlive/texmf-dist/doc/latex/dickimaw
share/texlive/texmf-dist/doc/latex/diffcoeff
share/texlive/texmf-dist/doc/latex/digiconfigs
share/texlive/texmf-dist/doc/latex/din1505
share/texlive/texmf-dist/doc/latex/dinbrief
share/texlive/texmf-dist/doc/latex/directory
share/texlive/texmf-dist/doc/latex/dirtytalk
share/texlive/texmf-dist/doc/latex/disser
share/texlive/texmf-dist/doc/latex/dithesis
share/texlive/texmf-dist/doc/latex/dk-bib
share/texlive/texmf-dist/doc/latex/dlfltxb
share/texlive/texmf-dist/doc/latex/dnaseq
share/texlive/texmf-dist/doc/latex/doclicense
share/texlive/texmf-dist/doc/latex/docmfp
share/texlive/texmf-dist/doc/latex/docmute
share/texlive/texmf-dist/doc/latex/docsurvey
share/texlive/texmf-dist/doc/latex/doctools
share/texlive/texmf-dist/doc/latex/documentation
share/texlive/texmf-dist/doc/latex/doi
share/texlive/texmf-dist/doc/latex/doipubmed
share/texlive/texmf-dist/doc/latex/dot2texi
share/texlive/texmf-dist/doc/latex/dotarrow
share/texlive/texmf-dist/doc/latex/dotseqn
share/texlive/texmf-dist/doc/latex/dottex
share/texlive/texmf-dist/doc/latex/download
share/texlive/texmf-dist/doc/latex/dox
share/texlive/texmf-dist/doc/latex/dpfloat
share/texlive/texmf-dist/doc/latex/dprogress
share/texlive/texmf-dist/doc/latex/drac
share/texlive/texmf-dist/doc/latex/draftcopy
share/texlive/texmf-dist/doc/latex/draftfigure
share/texlive/texmf-dist/doc/latex/draftwatermark
share/texlive/texmf-dist/doc/latex/dramatist
share/texlive/texmf-dist/doc/latex/drawmatrix
share/texlive/texmf-dist/doc/latex/drawstack
share/texlive/texmf-dist/doc/latex/droit-fr
share/texlive/texmf-dist/doc/latex/drs
share/texlive/texmf-dist/doc/latex/dsptricks
share/texlive/texmf-dist/doc/latex/dtk
share/texlive/texmf-dist/doc/latex/dtxdescribe
share/texlive/texmf-dist/doc/latex/dtxgallery
share/texlive/texmf-dist/doc/latex/dtxtut
share/texlive/texmf-dist/doc/latex/duerer-latex
share/texlive/texmf-dist/doc/latex/duotenzor
share/texlive/texmf-dist/doc/latex/dvdcoll
share/texlive/texmf-dist/doc/latex/dvgloss
share/texlive/texmf-dist/doc/latex/dviasm
share/texlive/texmf-dist/doc/latex/dynamicnumber
share/texlive/texmf-dist/doc/latex/dynblocks
share/texlive/texmf-dist/doc/latex/dyntree
share/texlive/texmf-dist/doc/latex/ean13isbn
share/texlive/texmf-dist/doc/latex/easy
share/texlive/texmf-dist/doc/latex/easy-todo
share/texlive/texmf-dist/doc/latex/easyfig
share/texlive/texmf-dist/doc/latex/easyformat
share/texlive/texmf-dist/doc/latex/easylist
share/texlive/texmf-dist/doc/latex/easyreview
share/texlive/texmf-dist/doc/latex/ebezier
share/texlive/texmf-dist/doc/latex/ebong
share/texlive/texmf-dist/doc/latex/ebook
share/texlive/texmf-dist/doc/latex/ebproof
share/texlive/texmf-dist/doc/latex/ebsthesis
share/texlive/texmf-dist/doc/latex/ecclesiastic
share/texlive/texmf-dist/doc/latex/ecgdraw
share/texlive/texmf-dist/doc/latex/ecltree
share/texlive/texmf-dist/doc/latex/ecobiblatex
share/texlive/texmf-dist/doc/latex/econometrics
share/texlive/texmf-dist/doc/latex/ecv
share/texlive/texmf-dist/doc/latex/ed
share/texlive/texmf-dist/doc/latex/edfnotes
share/texlive/texmf-dist/doc/latex/edmac
share/texlive/texmf-dist/doc/latex/edmargin
share/texlive/texmf-dist/doc/latex/ednotes
share/texlive/texmf-dist/doc/latex/eemeir
share/texlive/texmf-dist/doc/latex/eepic
share/texlive/texmf-dist/doc/latex/efbox
share/texlive/texmf-dist/doc/latex/egameps
share/texlive/texmf-dist/doc/latex/egplot
share/texlive/texmf-dist/doc/latex/eiad-ltx
share/texlive/texmf-dist/doc/latex/einfuehrung
share/texlive/texmf-dist/doc/latex/einfuehrung2
share/texlive/texmf-dist/doc/latex/ejpecp
share/texlive/texmf-dist/doc/latex/ekaia
share/texlive/texmf-dist/doc/latex/elbioimp
share/texlive/texmf-dist/doc/latex/eledform
share/texlive/texmf-dist/doc/latex/eledmac
share/texlive/texmf-dist/doc/latex/elements
share/texlive/texmf-dist/doc/latex/ellipse
share/texlive/texmf-dist/doc/latex/ellipsis
share/texlive/texmf-dist/doc/latex/elmath
share/texlive/texmf-dist/doc/latex/elocalloc
share/texlive/texmf-dist/doc/latex/elpres
share/texlive/texmf-dist/doc/latex/elsarticle
share/texlive/texmf-dist/doc/latex/elteikthesis
share/texlive/texmf-dist/doc/latex/eltex
share/texlive/texmf-dist/doc/latex/elzcards
share/texlive/texmf-dist/doc/latex/emarks
share/texlive/texmf-dist/doc/latex/embedall
share/texlive/texmf-dist/doc/latex/embrac
share/texlive/texmf-dist/doc/latex/emf
share/texlive/texmf-dist/doc/latex/emisa
share/texlive/texmf-dist/doc/latex/emp
share/texlive/texmf-dist/doc/latex/emptypage
share/texlive/texmf-dist/doc/latex/emulateapj
share/texlive/texmf-dist/doc/latex/endfloat
share/texlive/texmf-dist/doc/latex/endheads
share/texlive/texmf-dist/doc/latex/endiagram
share/texlive/texmf-dist/doc/latex/endnotes
share/texlive/texmf-dist/doc/latex/engpron
share/texlive/texmf-dist/doc/latex/engrec
share/texlive/texmf-dist/doc/latex/engtlc
share/texlive/texmf-dist/doc/latex/enotez
share/texlive/texmf-dist/doc/latex/enumitem
share/texlive/texmf-dist/doc/latex/enumitem-zref
share/texlive/texmf-dist/doc/latex/envbig
share/texlive/texmf-dist/doc/latex/environ
share/texlive/texmf-dist/doc/latex/envlab
share/texlive/texmf-dist/doc/latex/epigraph
share/texlive/texmf-dist/doc/latex/epiolmec
share/texlive/texmf-dist/doc/latex/epsdice
share/texlive/texmf-dist/doc/latex/epslatex-fr
share/texlive/texmf-dist/doc/latex/epspdfconversion
share/texlive/texmf-dist/doc/latex/eqell
share/texlive/texmf-dist/doc/latex/eqlist
share/texlive/texmf-dist/doc/latex/eqnalign
share/texlive/texmf-dist/doc/latex/eqnarray
share/texlive/texmf-dist/doc/latex/eqparbox
share/texlive/texmf-dist/doc/latex/erdc
share/texlive/texmf-dist/doc/latex/errata
share/texlive/texmf-dist/doc/latex/esami
share/texlive/texmf-dist/doc/latex/esdiff
share/texlive/texmf-dist/doc/latex/esint
share/texlive/texmf-dist/doc/latex/esk
share/texlive/texmf-dist/doc/latex/eskd
share/texlive/texmf-dist/doc/latex/eskdx
share/texlive/texmf-dist/doc/latex/eso-pic
share/texlive/texmf-dist/doc/latex/estcpmm
share/texlive/texmf-dist/doc/latex/esvect
share/texlive/texmf-dist/doc/latex/etaremune
share/texlive/texmf-dist/doc/latex/etdipa
share/texlive/texmf-dist/doc/latex/etex-pkg
share/texlive/texmf-dist/doc/latex/etextools
share/texlive/texmf-dist/doc/latex/ethiop
share/texlive/texmf-dist/doc/latex/ethiop-t1
share/texlive/texmf-dist/doc/latex/etoc
share/texlive/texmf-dist/doc/latex/etoolbox
share/texlive/texmf-dist/doc/latex/etoolbox-de
share/texlive/texmf-dist/doc/latex/euenc
share/texlive/texmf-dist/doc/latex/eukdate
share/texlive/texmf-dist/doc/latex/euler
share/texlive/texmf-dist/doc/latex/eulervm
share/texlive/texmf-dist/doc/latex/euro
share/texlive/texmf-dist/doc/latex/europasscv
share/texlive/texmf-dist/doc/latex/europecv
share/texlive/texmf-dist/doc/latex/everyhook
share/texlive/texmf-dist/doc/latex/everypage
share/texlive/texmf-dist/doc/latex/exam
share/texlive/texmf-dist/doc/latex/exam-n
share/texlive/texmf-dist/doc/latex/examdesign
share/texlive/texmf-dist/doc/latex/examplep
share/texlive/texmf-dist/doc/latex/exceltex
share/texlive/texmf-dist/doc/latex/excludeonly
share/texlive/texmf-dist/doc/latex/exercise
share/texlive/texmf-dist/doc/latex/exercises
share/texlive/texmf-dist/doc/latex/exp-testopt
share/texlive/texmf-dist/doc/latex/expdlist
share/texlive/texmf-dist/doc/latex/export
share/texlive/texmf-dist/doc/latex/exsheets
share/texlive/texmf-dist/doc/latex/exsol
share/texlive/texmf-dist/doc/latex/extarrows
share/texlive/texmf-dist/doc/latex/extpfeil
share/texlive/texmf-dist/doc/latex/extract
share/texlive/texmf-dist/doc/latex/extsizes
share/texlive/texmf-dist/doc/latex/facsimile
share/texlive/texmf-dist/doc/latex/factura
share/texlive/texmf-dist/doc/latex/faktor
share/texlive/texmf-dist/doc/latex/fancybox
share/texlive/texmf-dist/doc/latex/fancyhdr
share/texlive/texmf-dist/doc/latex/fancyhdr-it
share/texlive/texmf-dist/doc/latex/fancylabel
share/texlive/texmf-dist/doc/latex/fancynum
share/texlive/texmf-dist/doc/latex/fancypar
share/texlive/texmf-dist/doc/latex/fancyref
share/texlive/texmf-dist/doc/latex/fancyslides
share/texlive/texmf-dist/doc/latex/fancytabs
share/texlive/texmf-dist/doc/latex/fancytooltips
share/texlive/texmf-dist/doc/latex/fancyvrb
share/texlive/texmf-dist/doc/latex/fast-diagram
share/texlive/texmf-dist/doc/latex/fbithesis
share/texlive/texmf-dist/doc/latex/fcavtex
share/texlive/texmf-dist/doc/latex/fcltxdoc
share/texlive/texmf-dist/doc/latex/fcolumn
share/texlive/texmf-dist/doc/latex/fdsymbol
share/texlive/texmf-dist/doc/latex/fei
share/texlive/texmf-dist/doc/latex/feupphdteses
share/texlive/texmf-dist/doc/latex/feynmf
share/texlive/texmf-dist/doc/latex/feynmp-auto
share/texlive/texmf-dist/doc/latex/ffslides
share/texlive/texmf-dist/doc/latex/fgruler
share/texlive/texmf-dist/doc/latex/fibeamer
share/texlive/texmf-dist/doc/latex/fifinddo-info
share/texlive/texmf-dist/doc/latex/fifo-stack
share/texlive/texmf-dist/doc/latex/figbib
share/texlive/texmf-dist/doc/latex/figsize
share/texlive/texmf-dist/doc/latex/filecontents
share/texlive/texmf-dist/doc/latex/filecontentsdef
share/texlive/texmf-dist/doc/latex/filedate
share/texlive/texmf-dist/doc/latex/filehook
share/texlive/texmf-dist/doc/latex/fileinfo
share/texlive/texmf-dist/doc/latex/filemod
share/texlive/texmf-dist/doc/latex/fink
share/texlive/texmf-dist/doc/latex/finstrut
share/texlive/texmf-dist/doc/latex/first-latex-doc
share/texlive/texmf-dist/doc/latex/fitbox
share/texlive/texmf-dist/doc/latex/fithesis
share/texlive/texmf-dist/doc/latex/fix2col
share/texlive/texmf-dist/doc/latex/fixcmex
share/texlive/texmf-dist/doc/latex/fixfoot
share/texlive/texmf-dist/doc/latex/fixltxhyph
share/texlive/texmf-dist/doc/latex/fixme
share/texlive/texmf-dist/doc/latex/fixmetodonotes
share/texlive/texmf-dist/doc/latex/fjodor
share/texlive/texmf-dist/doc/latex/flabels
share/texlive/texmf-dist/doc/latex/flacards
share/texlive/texmf-dist/doc/latex/flagderiv
share/texlive/texmf-dist/doc/latex/flashcards
share/texlive/texmf-dist/doc/latex/flashmovie
share/texlive/texmf-dist/doc/latex/flipbook
share/texlive/texmf-dist/doc/latex/flippdf
share/texlive/texmf-dist/doc/latex/float
share/texlive/texmf-dist/doc/latex/floatflt
share/texlive/texmf-dist/doc/latex/floatrow
share/texlive/texmf-dist/doc/latex/flowchart
share/texlive/texmf-dist/doc/latex/flowfram
share/texlive/texmf-dist/doc/latex/fmp
share/texlive/texmf-dist/doc/latex/fmtcount
share/texlive/texmf-dist/doc/latex/fn2end
share/texlive/texmf-dist/doc/latex/fnbreak
share/texlive/texmf-dist/doc/latex/fncychap
share/texlive/texmf-dist/doc/latex/fncylab
share/texlive/texmf-dist/doc/latex/fnpara
share/texlive/texmf-dist/doc/latex/fnpct
share/texlive/texmf-dist/doc/latex/fnspe
share/texlive/texmf-dist/doc/latex/fnumprint
share/texlive/texmf-dist/doc/latex/foekfont
share/texlive/texmf-dist/doc/latex/foilhtml
share/texlive/texmf-dist/doc/latex/folders
share/texlive/texmf-dist/doc/latex/fontaxes
share/texlive/texmf-dist/doc/latex/fontspec
share/texlive/texmf-dist/doc/latex/fonttable
share/texlive/texmf-dist/doc/latex/footbib
share/texlive/texmf-dist/doc/latex/footmisc
share/texlive/texmf-dist/doc/latex/footmisx
share/texlive/texmf-dist/doc/latex/footnotebackref
share/texlive/texmf-dist/doc/latex/footnotehyper
share/texlive/texmf-dist/doc/latex/footnoterange
share/texlive/texmf-dist/doc/latex/footnpag
share/texlive/texmf-dist/doc/latex/forarray
share/texlive/texmf-dist/doc/latex/foreign
share/texlive/texmf-dist/doc/latex/forest
share/texlive/texmf-dist/doc/latex/forest-quickstart
share/texlive/texmf-dist/doc/latex/forloop
share/texlive/texmf-dist/doc/latex/formation-latex-ul
share/texlive/texmf-dist/doc/latex/formular
share/texlive/texmf-dist/doc/latex/fouridx
share/texlive/texmf-dist/doc/latex/fp
share/texlive/texmf-dist/doc/latex/fragments
share/texlive/texmf-dist/doc/latex/framed
share/texlive/texmf-dist/doc/latex/frankenstein
share/texlive/texmf-dist/doc/latex/frege
share/texlive/texmf-dist/doc/latex/frletter
share/texlive/texmf-dist/doc/latex/frontespizio
share/texlive/texmf-dist/doc/latex/ftcap
share/texlive/texmf-dist/doc/latex/ftnxtra
share/texlive/texmf-dist/doc/latex/fullblck
share/texlive/texmf-dist/doc/latex/fullminipage
share/texlive/texmf-dist/doc/latex/fullwidth
share/texlive/texmf-dist/doc/latex/functan
share/texlive/texmf-dist/doc/latex/fundus-calligra
share/texlive/texmf-dist/doc/latex/fundus-sueterlin
share/texlive/texmf-dist/doc/latex/fvextra
share/texlive/texmf-dist/doc/latex/fwlw
share/texlive/texmf-dist/doc/latex/g-brief
share/texlive/texmf-dist/doc/latex/gaceta
share/texlive/texmf-dist/doc/latex/galois
share/texlive/texmf-dist/doc/latex/gamebook
share/texlive/texmf-dist/doc/latex/gastex
share/texlive/texmf-dist/doc/latex/gatech-thesis
share/texlive/texmf-dist/doc/latex/gauss
share/texlive/texmf-dist/doc/latex/gb4e
share/texlive/texmf-dist/doc/latex/gcard
share/texlive/texmf-dist/doc/latex/gchords
share/texlive/texmf-dist/doc/latex/gcite
share/texlive/texmf-dist/doc/latex/gender
share/texlive/texmf-dist/doc/latex/gene-logic
share/texlive/texmf-dist/doc/latex/genealogytree
share/texlive/texmf-dist/doc/latex/genmpage
share/texlive/texmf-dist/doc/latex/geometry
share/texlive/texmf-dist/doc/latex/geometry-de
share/texlive/texmf-dist/doc/latex/germkorr
share/texlive/texmf-dist/doc/latex/geschichtsfrkl
share/texlive/texmf-dist/doc/latex/getfiledate
share/texlive/texmf-dist/doc/latex/getitems
share/texlive/texmf-dist/doc/latex/getmap
share/texlive/texmf-dist/doc/latex/ghab
share/texlive/texmf-dist/doc/latex/ghsystem
share/texlive/texmf-dist/doc/latex/gillcm
share/texlive/texmf-dist/doc/latex/gincltex
share/texlive/texmf-dist/doc/latex/ginpenc
share/texlive/texmf-dist/doc/latex/gitinfo
share/texlive/texmf-dist/doc/latex/gitinfo2
share/texlive/texmf-dist/doc/latex/gitlog
share/texlive/texmf-dist/doc/latex/gloss
share/texlive/texmf-dist/doc/latex/gloss-occitan
share/texlive/texmf-dist/doc/latex/glossaries
share/texlive/texmf-dist/doc/latex/glossaries-danish
share/texlive/texmf-dist/doc/latex/glossaries-dutch
share/texlive/texmf-dist/doc/latex/glossaries-english
share/texlive/texmf-dist/doc/latex/glossaries-extra
share/texlive/texmf-dist/doc/latex/glossaries-french
share/texlive/texmf-dist/doc/latex/glossaries-german
share/texlive/texmf-dist/doc/latex/glossaries-irish
share/texlive/texmf-dist/doc/latex/glossaries-italian
share/texlive/texmf-dist/doc/latex/glossaries-magyar
share/texlive/texmf-dist/doc/latex/glossaries-polish
share/texlive/texmf-dist/doc/latex/glossaries-portuges
share/texlive/texmf-dist/doc/latex/glossaries-serbian
share/texlive/texmf-dist/doc/latex/glossaries-spanish
share/texlive/texmf-dist/doc/latex/gmdoc
share/texlive/texmf-dist/doc/latex/gmdoc-enhance
share/texlive/texmf-dist/doc/latex/gmiflink
share/texlive/texmf-dist/doc/latex/gmp
share/texlive/texmf-dist/doc/latex/gmutils
share/texlive/texmf-dist/doc/latex/gmverb
share/texlive/texmf-dist/doc/latex/gmverse
share/texlive/texmf-dist/doc/latex/gnuplottex
share/texlive/texmf-dist/doc/latex/gotoh
share/texlive/texmf-dist/doc/latex/gradientframe
share/texlive/texmf-dist/doc/latex/gradstudentresume
share/texlive/texmf-dist/doc/latex/grafcet
share/texlive/texmf-dist/doc/latex/grant
share/texlive/texmf-dist/doc/latex/graphbox
share/texlive/texmf-dist/doc/latex/graphics
share/texlive/texmf-dist/doc/latex/graphics-cfg
share/texlive/texmf-dist/doc/latex/graphics-def
share/texlive/texmf-dist/doc/latex/graphicx-psmin
share/texlive/texmf-dist/doc/latex/graphicxbox
share/texlive/texmf-dist/doc/latex/graphviz
share/texlive/texmf-dist/doc/latex/grayhints
share/texlive/texmf-dist/doc/latex/greek-fontenc
share/texlive/texmf-dist/doc/latex/greek-inputenc
share/texlive/texmf-dist/doc/latex/greekdates
share/texlive/texmf-dist/doc/latex/greektonoi
share/texlive/texmf-dist/doc/latex/grfpaste
share/texlive/texmf-dist/doc/latex/grid
share/texlive/texmf-dist/doc/latex/grid-system
share/texlive/texmf-dist/doc/latex/gridset
share/texlive/texmf-dist/doc/latex/grundgesetze
share/texlive/texmf-dist/doc/latex/gsemthesis
share/texlive/texmf-dist/doc/latex/gtrcrd
share/texlive/texmf-dist/doc/latex/gtrlib-largetrees
share/texlive/texmf-dist/doc/latex/gu
share/texlive/texmf-dist/doc/latex/guide-to-latex
share/texlive/texmf-dist/doc/latex/guitar
share/texlive/texmf-dist/doc/latex/guitarchordschemes
share/texlive/texmf-dist/doc/latex/guitlogo
share/texlive/texmf-dist/doc/latex/gzt
share/texlive/texmf-dist/doc/latex/h2020proposal
share/texlive/texmf-dist/doc/latex/halloweenmath
share/texlive/texmf-dist/doc/latex/handout
share/texlive/texmf-dist/doc/latex/hang
share/texlive/texmf-dist/doc/latex/hanging
share/texlive/texmf-dist/doc/latex/har2nat
share/texlive/texmf-dist/doc/latex/hardwrap
share/texlive/texmf-dist/doc/latex/harmony
share/texlive/texmf-dist/doc/latex/harnon-cv
share/texlive/texmf-dist/doc/latex/harpoon
share/texlive/texmf-dist/doc/latex/harvard
share/texlive/texmf-dist/doc/latex/harveyballs
share/texlive/texmf-dist/doc/latex/hausarbeit-jura
share/texlive/texmf-dist/doc/latex/havannah
share/texlive/texmf-dist/doc/latex/hc
share/texlive/texmf-dist/doc/latex/he-she
share/texlive/texmf-dist/doc/latex/hep
share/texlive/texmf-dist/doc/latex/hepnames
share/texlive/texmf-dist/doc/latex/hepparticles
share/texlive/texmf-dist/doc/latex/hepthesis
share/texlive/texmf-dist/doc/latex/hepunits
share/texlive/texmf-dist/doc/latex/here
share/texlive/texmf-dist/doc/latex/hexgame
share/texlive/texmf-dist/doc/latex/hf-tikz
share/texlive/texmf-dist/doc/latex/hhtensor
share/texlive/texmf-dist/doc/latex/histogr
share/texlive/texmf-dist/doc/latex/historische-zeitschrift
share/texlive/texmf-dist/doc/latex/hitec
share/texlive/texmf-dist/doc/latex/hletter
share/texlive/texmf-dist/doc/latex/hobby
share/texlive/texmf-dist/doc/latex/hobete
share/texlive/texmf-dist/doc/latex/horoscop
share/texlive/texmf-dist/doc/latex/hpsdiss
share/texlive/texmf-dist/doc/latex/hrefhide
share/texlive/texmf-dist/doc/latex/hrlatex
share/texlive/texmf-dist/doc/latex/hustthesis
share/texlive/texmf-dist/doc/latex/hvfloat
share/texlive/texmf-dist/doc/latex/hvindex
share/texlive/texmf-dist/doc/latex/hypdvips
share/texlive/texmf-dist/doc/latex/hyper
share/texlive/texmf-dist/doc/latex/hypernat
share/texlive/texmf-dist/doc/latex/hyperref
share/texlive/texmf-dist/doc/latex/hyperref-docsrc
share/texlive/texmf-dist/doc/latex/hyperxmp
share/texlive/texmf-dist/doc/latex/hyphenat
share/texlive/texmf-dist/doc/latex/ibycus-babel
share/texlive/texmf-dist/doc/latex/icsv
share/texlive/texmf-dist/doc/latex/idxcmds
share/texlive/texmf-dist/doc/latex/idxlayout
share/texlive/texmf-dist/doc/latex/ieeepes
share/texlive/texmf-dist/doc/latex/ifetex
share/texlive/texmf-dist/doc/latex/iffont
share/texlive/texmf-dist/doc/latex/ifmslide
share/texlive/texmf-dist/doc/latex/ifmtarg
share/texlive/texmf-dist/doc/latex/ifnextok
share/texlive/texmf-dist/doc/latex/ifoddpage
share/texlive/texmf-dist/doc/latex/ifplatform
share/texlive/texmf-dist/doc/latex/ifthenx
share/texlive/texmf-dist/doc/latex/iitem
share/texlive/texmf-dist/doc/latex/ijmart
share/texlive/texmf-dist/doc/latex/ijsra
share/texlive/texmf-dist/doc/latex/imac
share/texlive/texmf-dist/doc/latex/image-gallery
share/texlive/texmf-dist/doc/latex/imakeidx
share/texlive/texmf-dist/doc/latex/impnattypo
share/texlive/texmf-dist/doc/latex/import
share/texlive/texmf-dist/doc/latex/imtekda
share/texlive/texmf-dist/doc/latex/incgraph
share/texlive/texmf-dist/doc/latex/index
share/texlive/texmf-dist/doc/latex/indextools
share/texlive/texmf-dist/doc/latex/inlinedef
share/texlive/texmf-dist/doc/latex/inputtrc
share/texlive/texmf-dist/doc/latex/interactiveworkbook
share/texlive/texmf-dist/doc/latex/interfaces
share/texlive/texmf-dist/doc/latex/interval
share/texlive/texmf-dist/doc/latex/intro-scientific
share/texlive/texmf-dist/doc/latex/inversepath
share/texlive/texmf-dist/doc/latex/invoice
share/texlive/texmf-dist/doc/latex/ionumbers
share/texlive/texmf-dist/doc/latex/iscram
share/texlive/texmf-dist/doc/latex/iso
share/texlive/texmf-dist/doc/latex/iso10303
share/texlive/texmf-dist/doc/latex/isodate
share/texlive/texmf-dist/doc/latex/isodoc
share/texlive/texmf-dist/doc/latex/isomath
share/texlive/texmf-dist/doc/latex/isonums
share/texlive/texmf-dist/doc/latex/isorot
share/texlive/texmf-dist/doc/latex/isotope
share/texlive/texmf-dist/doc/latex/issuulinks
share/texlive/texmf-dist/doc/latex/itnumpar
share/texlive/texmf-dist/doc/latex/iwhdp
share/texlive/texmf-dist/doc/latex/jacow
share/texlive/texmf-dist/doc/latex/jamtimes
share/texlive/texmf-dist/doc/latex/jknapltx
share/texlive/texmf-dist/doc/latex/jlabels
share/texlive/texmf-dist/doc/latex/jlreq
share/texlive/texmf-dist/doc/latex/jmlr
share/texlive/texmf-dist/doc/latex/jneurosci
share/texlive/texmf-dist/doc/latex/jpsj
share/texlive/texmf-dist/doc/latex/jslectureplanner
share/texlive/texmf-dist/doc/latex/jumplines
share/texlive/texmf-dist/doc/latex/jura
share/texlive/texmf-dist/doc/latex/juraabbrev
share/texlive/texmf-dist/doc/latex/jurabib
share/texlive/texmf-dist/doc/latex/juramisc
share/texlive/texmf-dist/doc/latex/jurarsp
share/texlive/texmf-dist/doc/latex/jvlisting
share/texlive/texmf-dist/doc/latex/kantlipsum
share/texlive/texmf-dist/doc/latex/karnaugh
share/texlive/texmf-dist/doc/latex/karnaugh-map
share/texlive/texmf-dist/doc/latex/karnaughmap
share/texlive/texmf-dist/doc/latex/kdgdocs
share/texlive/texmf-dist/doc/latex/kerkis
share/texlive/texmf-dist/doc/latex/kerntest
share/texlive/texmf-dist/doc/latex/keycommand
share/texlive/texmf-dist/doc/latex/keyfloat
share/texlive/texmf-dist/doc/latex/keyreader
share/texlive/texmf-dist/doc/latex/keystroke
share/texlive/texmf-dist/doc/latex/keyval2e
share/texlive/texmf-dist/doc/latex/keyvaltable
share/texlive/texmf-dist/doc/latex/kix
share/texlive/texmf-dist/doc/latex/kluwer
share/texlive/texmf-dist/doc/latex/knittingpattern
share/texlive/texmf-dist/doc/latex/koma-moderncvclassic
share/texlive/texmf-dist/doc/latex/koma-script
share/texlive/texmf-dist/doc/latex/koma-script-examples
share/texlive/texmf-dist/doc/latex/koma-script-sfs
share/texlive/texmf-dist/doc/latex/komacv
share/texlive/texmf-dist/doc/latex/kotex-oblivoir
share/texlive/texmf-dist/doc/latex/kotex-utf
share/texlive/texmf-dist/doc/latex/kotex-utils
share/texlive/texmf-dist/doc/latex/ksp-thesis
share/texlive/texmf-dist/doc/latex/ktv-texdata
share/texlive/texmf-dist/doc/latex/l2picfaq
share/texlive/texmf-dist/doc/latex/l2tabu
share/texlive/texmf-dist/doc/latex/l2tabu-english
share/texlive/texmf-dist/doc/latex/l2tabu-french
share/texlive/texmf-dist/doc/latex/l2tabu-italian
share/texlive/texmf-dist/doc/latex/l2tabu-spanish
share/texlive/texmf-dist/doc/latex/l3build
share/texlive/texmf-dist/doc/latex/l3experimental
share/texlive/texmf-dist/doc/latex/l3kernel
share/texlive/texmf-dist/doc/latex/l3packages
share/texlive/texmf-dist/doc/latex/labbook
share/texlive/texmf-dist/doc/latex/labels
share/texlive/texmf-dist/doc/latex/labyrinth
share/texlive/texmf-dist/doc/latex/ladder
share/texlive/texmf-dist/doc/latex/lapdf
share/texlive/texmf-dist/doc/latex/lastpackage
share/texlive/texmf-dist/doc/latex/lastpage
share/texlive/texmf-dist/doc/latex/latex-bib-ex
share/texlive/texmf-dist/doc/latex/latex-bib2-ex
share/texlive/texmf-dist/doc/latex/latex-brochure
share/texlive/texmf-dist/doc/latex/latex-course
share/texlive/texmf-dist/doc/latex/latex-doc-ptr
share/texlive/texmf-dist/doc/latex/latex-graphics-companion
share/texlive/texmf-dist/doc/latex/latex-referenz
share/texlive/texmf-dist/doc/latex/latex-tabellen
share/texlive/texmf-dist/doc/latex/latex-tds
share/texlive/texmf-dist/doc/latex/latex-veryshortguide
share/texlive/texmf-dist/doc/latex/latex-web-companion
share/texlive/texmf-dist/doc/latex/latex2e-help-texinfo
share/texlive/texmf-dist/doc/latex/latex2e-help-texinfo-fr
share/texlive/texmf-dist/doc/latex/latex2e-help-texinfo-spanish
share/texlive/texmf-dist/doc/latex/latex4wp"
