TERMUX_SUBPKG_DESCRIPTION="Documentation for all of TeX Lives packages except for the latex packages. Contains texmf-dist/doc."
TERMUX_SUBPKG_DEPENDS="texlive-full"
TERMUX_SUBPKG_INCLUDE="share/texlive/texmf-dist/doc/aleph
share/texlive/texmf-dist/doc/amstex
share/texlive/texmf-dist/doc/asymptote
share/texlive/texmf-dist/doc/bibtex
share/texlive/texmf-dist/doc/bibtexu
share/texlive/texmf-dist/doc/context
share/texlive/texmf-dist/doc/cstex
share/texlive/texmf-dist/doc/dvipdfm
share/texlive/texmf-dist/doc/dvipdfmx
share/texlive/texmf-dist/doc/dvipng
share/texlive/texmf-dist/doc/dvips
share/texlive/texmf-dist/doc/eplain
share/texlive/texmf-dist/doc/etex
share/texlive/texmf-dist/doc/fonts
share/texlive/texmf-dist/doc/generic
share/texlive/texmf-dist/doc/info
share/texlive/texmf-dist/doc/kpathsea
share/texlive/texmf-dist/doc/lualatex
share/texlive/texmf-dist/doc/luatex
share/texlive/texmf-dist/doc/man
share/texlive/texmf-dist/doc/metapost
share/texlive/texmf-dist/doc/mex
share/texlive/texmf-dist/doc/omega
share/texlive/texmf-dist/doc/otherformats
share/texlive/texmf-dist/doc/pdftex
share/texlive/texmf-dist/doc/plain
share/texlive/texmf-dist/doc/platex
share/texlive/texmf-dist/doc/pmxchords
share/texlive/texmf-dist/doc/ptex
share/texlive/texmf-dist/doc/support
share/texlive/texmf-dist/doc/tetex
share/texlive/texmf-dist/doc/texdoc
share/texlive/texmf-dist/doc/texlive
share/texlive/texmf-dist/doc/texworks
share/texlive/texmf-dist/doc/tpic2pdftex
share/texlive/texmf-dist/doc/ttf2pk
share/texlive/texmf-dist/doc/uplatex
share/texlive/texmf-dist/doc/upmendex
share/texlive/texmf-dist/doc/uptex
share/texlive/texmf-dist/doc/vlna
share/texlive/texmf-dist/doc/web2c
share/texlive/texmf-dist/doc/xelatex
share/texlive/texmf-dist/doc/xetex
share/texlive/texmf-dist/doc/xindy"
